import { ALBUM_MASTER, USER_VINYL } from './db';

export type MockVinylData = ALBUM_MASTER & USER_VINYL;

export const mockVinyls: MockVinylData[] = [
  {
    ALBUM_ID: 1,
    USER_VINYL_ID: 101,
    USER_ID: 1,
    TITLE: "Kind of Blue",
    ARTIST: "Miles Davis",
    RELEASE_YEAR: 1959,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/9/9c/MilesDavisKindofBlue.jpg",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#1a1a1a",
    CUSTOM_STYLE_TYPE: "SOLID",
    STATUS: "OWNED",
    PURCHASE_DATE: "2023-01-15",
    PURCHASE_PRICE: 35.00,
    TRACKS: ["So What", "Freddie Freeloader", "Blue in Green", "All Blues", "Flamenco Sketches"]
  },
  {
    ALBUM_ID: 2,
    USER_VINYL_ID: 102,
    USER_ID: 1,
    TITLE: "Abbey Road",
    ARTIST: "The Beatles",
    RELEASE_YEAR: 1969,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/4/42/Beatles_-_Abbey_Road.jpg",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#000000",
    CUSTOM_STYLE_TYPE: "SOLID",
    STATUS: "OWNED",
    PURCHASE_DATE: "2023-05-20",
    PURCHASE_PRICE: 40.00,
    TRACKS: ["Come Together", "Something", "Maxwell's Silver Hammer", "Oh! Darling", "Octopus's Garden", "I Want You (She's So Heavy)", "Here Comes the Sun", "Because", "You Never Give Me Your Money"]
  },
  {
    ALBUM_ID: 3,
    USER_VINYL_ID: 103,
    USER_ID: 1,
    TITLE: "Rumours",
    ARTIST: "Fleetwood Mac",
    RELEASE_YEAR: 1977,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/f/fb/FMacRumours.PNG",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#e6e6e6",
    CUSTOM_STYLE_TYPE: "TRANSLUCENT",
    STATUS: "WISH",
    PURCHASE_DATE: "",
    PURCHASE_PRICE: 0,
    TRACKS: ["Second Hand News", "Dreams", "Never Going Back Again", "Don't Stop", "Go Your Own Way", "Songbird", "The Chain", "You Make Loving Fun", "I Don't Want to Know", "Oh Daddy", "Gold Dust Woman"]
  },
  {
    ALBUM_ID: 4,
    USER_VINYL_ID: 104,
    USER_ID: 1,
    TITLE: "The Dark Side of the Moon",
    ARTIST: "Pink Floyd",
    RELEASE_YEAR: 1973,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/3/3b/Dark_Side_of_the_Moon.png",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#000000",
    CUSTOM_STYLE_TYPE: "SOLID",
    STATUS: "OWNED",
    PURCHASE_DATE: "2024-02-10",
    PURCHASE_PRICE: 45.00,
    TRACKS: ["Speak to Me", "Breathe", "On the Run", "Time", "The Great Gig in the Sky", "Money", "Us and Them", "Any Colour You Like", "Brain Damage", "Eclipse"]
  },
  {
    ALBUM_ID: 5,
    USER_VINYL_ID: 105,
    USER_ID: 1,
    TITLE: "Thriller",
    ARTIST: "Michael Jackson",
    RELEASE_YEAR: 1982,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/5/55/Michael_Jackson_-_Thriller.png",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#ff0000",
    CUSTOM_STYLE_TYPE: "SPLATTER",
    STATUS: "WISH",
    PURCHASE_DATE: "",
    PURCHASE_PRICE: 0,
    TRACKS: ["Wanna Be Startin' Somethin'", "Baby Be Mine", "The Girl Is Mine", "Thriller", "Beat It", "Billie Jean", "Human Nature", "P.Y.T. (Pretty Young Thing)", "The Lady in My Life"]
  },
  {
    ALBUM_ID: 6,
    USER_VINYL_ID: 106,
    USER_ID: 1,
    TITLE: "Purple Rain",
    ARTIST: "Prince and The Revolution",
    RELEASE_YEAR: 1984,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/9/9c/Princepurplerain.jpg",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#800080",
    CUSTOM_STYLE_TYPE: "TRANSLUCENT",
    STATUS: "OWNED",
    PURCHASE_DATE: "2023-11-22",
    PURCHASE_PRICE: 28.00,
    TRACKS: ["Let's Go Crazy", "Take Me with U", "The Beautiful Ones", "Computer Blue", "Darling Nikki", "When Doves Cry", "I Would Die 4 U", "Baby I'm a Star", "Purple Rain"]
  },
  {
    ALBUM_ID: 7,
    USER_VINYL_ID: 107,
    USER_ID: 1,
    TITLE: "Back to Black",
    ARTIST: "Amy Winehouse",
    RELEASE_YEAR: 2006,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/6/67/Amy_Winehouse_-_Back_to_Black_%28album%29.png",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#000000",
    CUSTOM_STYLE_TYPE: "SOLID",
    STATUS: "OWNED",
    PURCHASE_DATE: "2022-08-05",
    PURCHASE_PRICE: 32.00,
    TRACKS: ["Rehab", "You Know I'm No Good", "Me & Mr Jones", "Just Friends", "Back to Black", "Love Is a Losing Game", "Tears Dry on Their Own", "Wake Up Alone", "Some Unholy War", "He Can Only Hold Her"]
  },
  {
    ALBUM_ID: 8,
    USER_VINYL_ID: 108,
    USER_ID: 1,
    TITLE: "Random Access Memories",
    ARTIST: "Daft Punk",
    RELEASE_YEAR: 2013,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/a/a7/Random_Access_Memories.jpg",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#000000",
    CUSTOM_STYLE_TYPE: "SOLID",
    STATUS: "WISH",
    PURCHASE_DATE: "",
    PURCHASE_PRICE: 0,
    TRACKS: ["Give Life Back to Music", "The Game of Love", "Giorgio by Moroder", "Within", "Instant Crush", "Lose Yourself to Dance", "Touch", "Get Lucky", "Beyond", "Motherboard", "Fragments of Time", "Doin' It Right", "Contact"]
  },
  {
    ALBUM_ID: 9,
    USER_VINYL_ID: 109,
    USER_ID: 1,
    TITLE: "To Pimp a Butterfly",
    ARTIST: "Kendrick Lamar",
    RELEASE_YEAR: 2015,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/f/f6/Kendrick_Lamar_-_To_Pimp_a_Butterfly.png",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#000000",
    CUSTOM_STYLE_TYPE: "SOLID",
    STATUS: "OWNED",
    PURCHASE_DATE: "2023-04-12",
    PURCHASE_PRICE: 38.00,
    TRACKS: ["Wesley's Theory", "For Free? (Interlude)", "King Kunta", "Institutionalized", "These Walls", "u", "Alright", "For Sale? (Interlude)", "Momma", "Hood Politics", "How Much a Dollar Cost", "Complexion (A Zulu Love)", "The Blacker the Berry", "You Ain't Gotta Lie (Momma Said)", "i", "Mortal Man"]
  },
  {
    ALBUM_ID: 10,
    USER_VINYL_ID: 110,
    USER_ID: 1,
    TITLE: "IGOR",
    ARTIST: "Tyler, The Creator",
    RELEASE_YEAR: 2019,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/5/51/Igor_-_Tyler%2C_the_Creator.jpg",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#ffb6c1",
    CUSTOM_STYLE_TYPE: "TRANSLUCENT",
    STATUS: "WISH",
    PURCHASE_DATE: "",
    PURCHASE_PRICE: 0,
    TRACKS: ["IGOR'S THEME", "EARFQUAKE", "I THINK", "EXACTLY WHAT YOU RUN FROM YOU END UP CHASING", "RUNNING OUT OF TIME", "NEW MAGIC WAND", "A BOY IS A GUN*", "PUPPET", "WHAT'S GOOD", "GONE, GONE / THANK YOU", "I DON'T LOVE YOU ANYMORE", "ARE WE STILL FRIENDS?"]
  }
];
