import { ALBUM_MASTER, USER_VINYL } from './db';

// USER_VINYL side is partial: search results and scan candidates are albums
// the user doesn't own yet, so ownership fields may be absent.
export type MockVinylData = ALBUM_MASTER & Partial<USER_VINYL>;

export const mockVinyls: MockVinylData[] = [
  {
    ALBUM_ID: 1,
    USER_VINYL_ID: 101,
    USER_ID: 1,
    TITLE: "Kind of Blue",
    ARTIST: "Miles Davis",
    RELEASE_YEAR: 1959,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/9/9c/MilesDavisKindofBlue.jpg",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#1a1a1a",
    CUSTOM_STYLE_TYPE: "SOLID",
    STATUS: "OWNED",
    PURCHASE_DATE: "2023-01-15",
    PURCHASE_PRICE: 35.00,
    TRACKS: [{ title: "So What" }, { title: "Freddie Freeloader" }, { title: "Blue in Green" }, { title: "All Blues" }, { title: "Flamenco Sketches" }]
  },
  {
    ALBUM_ID: 2,
    USER_VINYL_ID: 102,
    USER_ID: 1,
    TITLE: "Abbey Road",
    ARTIST: "The Beatles",
    RELEASE_YEAR: 1969,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/4/42/Beatles_-_Abbey_Road.jpg",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#000000",
    CUSTOM_STYLE_TYPE: "SOLID",
    STATUS: "OWNED",
    PURCHASE_DATE: "2023-05-20",
    PURCHASE_PRICE: 40.00,
    TRACKS: [{ title: "Come Together" }, { title: "Something" }, { title: "Maxwell's Silver Hammer" }, { title: "Oh! Darling" }, { title: "Octopus's Garden" }, { title: "I Want You (She's So Heavy)" }, { title: "Here Comes the Sun" }, { title: "Because" }, { title: "You Never Give Me Your Money" }]
  },
  {
    ALBUM_ID: 3,
    USER_VINYL_ID: 103,
    USER_ID: 1,
    TITLE: "Rumours",
    ARTIST: "Fleetwood Mac",
    RELEASE_YEAR: 1977,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/f/fb/FMacRumours.PNG",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#e6e6e6",
    CUSTOM_STYLE_TYPE: "TRANSLUCENT",
    STATUS: "WISH",
    PURCHASE_DATE: "",
    PURCHASE_PRICE: 0,
    TRACKS: [{ title: "Second Hand News" }, { title: "Dreams" }, { title: "Never Going Back Again" }, { title: "Don't Stop" }, { title: "Go Your Own Way" }, { title: "Songbird" }, { title: "The Chain" }, { title: "You Make Loving Fun" }, { title: "I Don't Want to Know" }, { title: "Oh Daddy" }, { title: "Gold Dust Woman" }]
  },
  {
    ALBUM_ID: 4,
    USER_VINYL_ID: 104,
    USER_ID: 1,
    TITLE: "The Dark Side of the Moon",
    ARTIST: "Pink Floyd",
    RELEASE_YEAR: 1973,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/3/3b/Dark_Side_of_the_Moon.png",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#000000",
    CUSTOM_STYLE_TYPE: "SOLID",
    STATUS: "OWNED",
    PURCHASE_DATE: "2024-02-10",
    PURCHASE_PRICE: 45.00,
    TRACKS: [{ title: "Speak to Me" }, { title: "Breathe" }, { title: "On the Run" }, { title: "Time" }, { title: "The Great Gig in the Sky" }, { title: "Money" }, { title: "Us and Them" }, { title: "Any Colour You Like" }, { title: "Brain Damage" }, { title: "Eclipse" }]
  },
  {
    ALBUM_ID: 5,
    USER_VINYL_ID: 105,
    USER_ID: 1,
    TITLE: "Thriller",
    ARTIST: "Michael Jackson",
    RELEASE_YEAR: 1982,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/5/55/Michael_Jackson_-_Thriller.png",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#ff0000",
    CUSTOM_STYLE_TYPE: "SPLATTER",
    STATUS: "WISH",
    PURCHASE_DATE: "",
    PURCHASE_PRICE: 0,
    TRACKS: [{ title: "Wanna Be Startin' Somethin'" }, { title: "Baby Be Mine" }, { title: "The Girl Is Mine" }, { title: "Thriller" }, { title: "Beat It" }, { title: "Billie Jean" }, { title: "Human Nature" }, { title: "P.Y.T. (Pretty Young Thing)" }, { title: "The Lady in My Life" }]
  },
  {
    ALBUM_ID: 6,
    USER_VINYL_ID: 106,
    USER_ID: 1,
    TITLE: "Purple Rain",
    ARTIST: "Prince and The Revolution",
    RELEASE_YEAR: 1984,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/9/9c/Princepurplerain.jpg",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#800080",
    CUSTOM_STYLE_TYPE: "TRANSLUCENT",
    STATUS: "OWNED",
    PURCHASE_DATE: "2023-11-22",
    PURCHASE_PRICE: 28.00,
    TRACKS: [{ title: "Let's Go Crazy" }, { title: "Take Me with U" }, { title: "The Beautiful Ones" }, { title: "Computer Blue" }, { title: "Darling Nikki" }, { title: "When Doves Cry" }, { title: "I Would Die 4 U" }, { title: "Baby I'm a Star" }, { title: "Purple Rain" }]
  },
  {
    ALBUM_ID: 7,
    USER_VINYL_ID: 107,
    USER_ID: 1,
    TITLE: "Back to Black",
    ARTIST: "Amy Winehouse",
    RELEASE_YEAR: 2006,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/6/67/Amy_Winehouse_-_Back_to_Black_%28album%29.png",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#000000",
    CUSTOM_STYLE_TYPE: "SOLID",
    STATUS: "OWNED",
    PURCHASE_DATE: "2022-08-05",
    PURCHASE_PRICE: 32.00,
    TRACKS: [{ title: "Rehab" }, { title: "You Know I'm No Good" }, { title: "Me & Mr Jones" }, { title: "Just Friends" }, { title: "Back to Black" }, { title: "Love Is a Losing Game" }, { title: "Tears Dry on Their Own" }, { title: "Wake Up Alone" }, { title: "Some Unholy War" }, { title: "He Can Only Hold Her" }]
  },
  {
    ALBUM_ID: 8,
    USER_VINYL_ID: 108,
    USER_ID: 1,
    TITLE: "Random Access Memories",
    ARTIST: "Daft Punk",
    RELEASE_YEAR: 2013,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/a/a7/Random_Access_Memories.jpg",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#000000",
    CUSTOM_STYLE_TYPE: "SOLID",
    STATUS: "WISH",
    PURCHASE_DATE: "",
    PURCHASE_PRICE: 0,
    TRACKS: [{ title: "Give Life Back to Music" }, { title: "The Game of Love" }, { title: "Giorgio by Moroder" }, { title: "Within" }, { title: "Instant Crush" }, { title: "Lose Yourself to Dance" }, { title: "Touch" }, { title: "Get Lucky" }, { title: "Beyond" }, { title: "Motherboard" }, { title: "Fragments of Time" }, { title: "Doin' It Right" }, { title: "Contact" }]
  },
  {
    ALBUM_ID: 9,
    USER_VINYL_ID: 109,
    USER_ID: 1,
    TITLE: "To Pimp a Butterfly",
    ARTIST: "Kendrick Lamar",
    RELEASE_YEAR: 2015,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/f/f6/Kendrick_Lamar_-_To_Pimp_a_Butterfly.png",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#000000",
    CUSTOM_STYLE_TYPE: "SOLID",
    STATUS: "OWNED",
    PURCHASE_DATE: "2023-04-12",
    PURCHASE_PRICE: 38.00,
    TRACKS: [{ title: "Wesley's Theory" }, { title: "For Free? (Interlude)" }, { title: "King Kunta" }, { title: "Institutionalized" }, { title: "These Walls" }, { title: "u" }, { title: "Alright" }, { title: "For Sale? (Interlude)" }, { title: "Momma" }, { title: "Hood Politics" }, { title: "How Much a Dollar Cost" }, { title: "Complexion (A Zulu Love)" }, { title: "The Blacker the Berry" }, { title: "You Ain't Gotta Lie (Momma Said)" }, { title: "i" }, { title: "Mortal Man" }]
  },
  {
    ALBUM_ID: 10,
    USER_VINYL_ID: 110,
    USER_ID: 1,
    TITLE: "IGOR",
    ARTIST: "Tyler, The Creator",
    RELEASE_YEAR: 2019,
    IMAGE_URL: "https://upload.wikimedia.org/wikipedia/en/5/51/Igor_-_Tyler%2C_the_Creator.jpg",
    VINYL_IMAGE_URL: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vinyl_record.svg",
    CUSTOM_COLOR_HEX: "#ffb6c1",
    CUSTOM_STYLE_TYPE: "TRANSLUCENT",
    STATUS: "WISH",
    PURCHASE_DATE: "",
    PURCHASE_PRICE: 0,
    TRACKS: [{ title: "IGOR'S THEME" }, { title: "EARFQUAKE" }, { title: "I THINK" }, { title: "EXACTLY WHAT YOU RUN FROM YOU END UP CHASING" }, { title: "RUNNING OUT OF TIME" }, { title: "NEW MAGIC WAND" }, { title: "A BOY IS A GUN*" }, { title: "PUPPET" }, { title: "WHAT'S GOOD" }, { title: "GONE, GONE / THANK YOU" }, { title: "I DON'T LOVE YOU ANYMORE" }, { title: "ARE WE STILL FRIENDS?" }]
  }
];
