-- 커뮤니티 게시판 (2026-08-02)
-- Run this whole file manually in the Supabase SQL Editor.
--
-- 6개 카테고리(오늘 온 전리품/자유/QnA/정보/나만의 청음실/팁)를 한 테이블로
-- 묶고 CATEGORY로 구분한다 — 카테고리마다 별 테이블을 두면 목록/검색/신고가
-- 전부 N배로 늘어나고, 다섯 카테고리는 실제로 "제목+사진+본문"으로 완전히
-- 동일한 입력이라 분리할 이유가 없다. 카테고리별 전용 필드(오늘 온 전리품의
-- 앨범 다중 첨부, 정보 게시판의 위치, QnA의 채택 답변)만 컬럼/조인 테이블로
-- 추가한다. 댓글도 "답변"과 한 테이블(COMMUNITY_COMMENT)을 공유한다 — QnA는
-- UI에서만 "답변"으로 부르고 채택 여부(COMMUNITY_POST.ACCEPTED_COMMENT_ID)만
-- 얹는다, 데이터 모양 자체는 자유게시판 댓글과 동일(PARENT_COMMENT_ID 1단계
-- 스레딩 — SPIN_LOG_COMMENT/VINYL_COMMENT와 같은 패턴).
--
-- 커뮤니티 게시글은 항상 전체 공개다(비공개 옵션 없음) — community-albums와
-- 같은 이유: 게시판은 애초에 공유가 목적이라 프로필 공개 여부와 무관하게
-- 노출되어야 한다.

CREATE TABLE IF NOT EXISTS public."COMMUNITY_POST" (
    "POST_ID"            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CATEGORY"           text NOT NULL,
    "TITLE"              text NOT NULL CHECK (char_length("TITLE") BETWEEN 1 AND 100),
    "CONTENT"            text NOT NULL CHECK (char_length("CONTENT") BETWEEN 1 AND 5000),
    -- [{ "url": "https://...", "type": "image" }, ...] — NOTICE.MEDIA_ITEMS와 동일 모양
    -- (영상은 v1 범위 밖이라 type은 항상 "image"지만, 추후 확장 여지를 위해
    -- 별도 컬럼 대신 NOTICE와 같은 구조를 그대로 재사용한다).
    "MEDIA_ITEMS"        jsonb NOT NULL DEFAULT '[]'::jsonb,
    "AUTHOR_ID"          uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "VIEW_COUNT"         integer NOT NULL DEFAULT 0,
    -- QnA 전용: 질문 작성자가 채택한 답변(최상위 답변만, 대댓글은 채택 불가).
    -- FK는 COMMUNITY_COMMENT 생성 후 아래에서 ALTER TABLE로 추가(순환 참조).
    "ACCEPTED_COMMENT_ID" bigint,
    -- 정보 게시판 전용 위치 공유(구글맵 Places 선택 결과).
    "PLACE_NAME"         text,
    "PLACE_ADDRESS"      text,
    "LATITUDE"           double precision,
    "LONGITUDE"          double precision,
    "CREATED_AT"         timestamp with time zone DEFAULT now(),
    "UPDATED_AT"         timestamp with time zone DEFAULT now(),
    CONSTRAINT "community_post_category_check" CHECK ("CATEGORY" IN ('ARRIVAL', 'FREE', 'QNA', 'INFO', 'LISTENING_ROOM', 'TIP')),
    CONSTRAINT "community_post_media_items_is_array" CHECK (jsonb_typeof("MEDIA_ITEMS") = 'array'),
    CONSTRAINT "community_post_media_items_max_5" CHECK (jsonb_array_length("MEDIA_ITEMS") <= 5),
    -- 위치 필드는 정보 게시판에서만 채워진다 — 다른 카테고리에서 실수로/악의적으로
    -- 채워 넣는 것을 DB 레벨에서 막는다.
    CONSTRAINT "community_post_location_only_info" CHECK (
      "CATEGORY" = 'INFO' OR (
        "PLACE_NAME" IS NULL AND "PLACE_ADDRESS" IS NULL AND "LATITUDE" IS NULL AND "LONGITUDE" IS NULL
      )
    )
);

CREATE INDEX IF NOT EXISTS "idx_community_post_category_created"
  ON public."COMMUNITY_POST" ("CATEGORY", "CREATED_AT" DESC);
CREATE INDEX IF NOT EXISTS "idx_community_post_author"
  ON public."COMMUNITY_POST" ("AUTHOR_ID");

ALTER TABLE public."COMMUNITY_POST" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "community_post_read_all"     ON public."COMMUNITY_POST";
DROP POLICY IF EXISTS "community_post_insert_own"   ON public."COMMUNITY_POST";
DROP POLICY IF EXISTS "community_post_update_own"   ON public."COMMUNITY_POST";
DROP POLICY IF EXISTS "community_post_delete_own_or_admin" ON public."COMMUNITY_POST";
CREATE POLICY "community_post_read_all" ON public."COMMUNITY_POST" FOR SELECT USING (true);
CREATE POLICY "community_post_insert_own" ON public."COMMUNITY_POST" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = "AUTHOR_ID");
CREATE POLICY "community_post_update_own" ON public."COMMUNITY_POST" FOR UPDATE TO authenticated
  USING ((select auth.uid()) = "AUTHOR_ID")
  WITH CHECK ((select auth.uid()) = "AUTHOR_ID");
CREATE POLICY "community_post_delete_own_or_admin" ON public."COMMUNITY_POST" FOR DELETE TO authenticated
  USING (
    (select auth.uid()) = "AUTHOR_ID"
    OR (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

-- ── 오늘 온 전리품: 본인 컬렉션 앨범 다중 첨부 (다대다) ─────────────────

CREATE TABLE IF NOT EXISTS public."COMMUNITY_POST_ALBUM" (
    "POST_ALBUM_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "POST_ID"       bigint NOT NULL REFERENCES public."COMMUNITY_POST"("POST_ID") ON DELETE CASCADE,
    "ALBUM_ID"      bigint NOT NULL REFERENCES public."ALBUM_MASTER"("ALBUM_ID"),
    CONSTRAINT "community_post_album_unique" UNIQUE ("POST_ID", "ALBUM_ID")
);
CREATE INDEX IF NOT EXISTS "idx_community_post_album_post" ON public."COMMUNITY_POST_ALBUM" ("POST_ID");

ALTER TABLE public."COMMUNITY_POST_ALBUM" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "community_post_album_read_all"  ON public."COMMUNITY_POST_ALBUM";
DROP POLICY IF EXISTS "community_post_album_insert_own" ON public."COMMUNITY_POST_ALBUM";
DROP POLICY IF EXISTS "community_post_album_delete_own" ON public."COMMUNITY_POST_ALBUM";
CREATE POLICY "community_post_album_read_all" ON public."COMMUNITY_POST_ALBUM" FOR SELECT USING (true);
-- 글쓴이 본인 + 오늘 온 전리품 카테고리에서만 첨부 가능 — 다른 카테고리 글에
-- 앨범을 몰래 엮는 것을 막는다.
CREATE POLICY "community_post_album_insert_own" ON public."COMMUNITY_POST_ALBUM" FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public."COMMUNITY_POST" p
      WHERE p."POST_ID" = "COMMUNITY_POST_ALBUM"."POST_ID"
        AND p."AUTHOR_ID" = (select auth.uid())
        AND p."CATEGORY" = 'ARRIVAL'
    )
  );
CREATE POLICY "community_post_album_delete_own" ON public."COMMUNITY_POST_ALBUM" FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public."COMMUNITY_POST" p
      WHERE p."POST_ID" = "COMMUNITY_POST_ALBUM"."POST_ID" AND p."AUTHOR_ID" = (select auth.uid())
    )
  );

-- ── 댓글(자유/정보/청음실/팁) 겸 답변(QnA) — 1단계 대댓글 스레딩 ─────────

CREATE TABLE IF NOT EXISTS public."COMMUNITY_COMMENT" (
    "COMMENT_ID"        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "POST_ID"           bigint NOT NULL REFERENCES public."COMMUNITY_POST"("POST_ID") ON DELETE CASCADE,
    "USER_ID"           uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "PARENT_COMMENT_ID" bigint REFERENCES public."COMMUNITY_COMMENT"("COMMENT_ID") ON DELETE CASCADE,
    "CONTENT"           text NOT NULL CHECK (char_length("CONTENT") BETWEEN 1 AND 1000),
    "CREATED_AT"        timestamp with time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_community_comment_post" ON public."COMMUNITY_COMMENT" ("POST_ID", "CREATED_AT");

ALTER TABLE public."COMMUNITY_COMMENT" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "community_comment_read_all"  ON public."COMMUNITY_COMMENT";
DROP POLICY IF EXISTS "community_comment_insert_own" ON public."COMMUNITY_COMMENT";
DROP POLICY IF EXISTS "community_comment_delete_own_or_post_owner" ON public."COMMUNITY_COMMENT";
CREATE POLICY "community_comment_read_all" ON public."COMMUNITY_COMMENT" FOR SELECT USING (true);
CREATE POLICY "community_comment_insert_own" ON public."COMMUNITY_COMMENT" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = "USER_ID");
-- 삭제 = 댓글 작성자 본인 OR 게시글 작성자(본인 글의 부적절한 댓글 정리) OR 관리자
CREATE POLICY "community_comment_delete_own_or_post_owner" ON public."COMMUNITY_COMMENT" FOR DELETE TO authenticated
  USING (
    (select auth.uid()) = "USER_ID"
    OR (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    OR EXISTS (
      SELECT 1 FROM public."COMMUNITY_POST" p
      WHERE p."POST_ID" = "COMMUNITY_COMMENT"."POST_ID" AND p."AUTHOR_ID" = (select auth.uid())
    )
  );

-- 이제 COMMUNITY_COMMENT가 존재하므로 ACCEPTED_COMMENT_ID FK를 건다.
-- ADD CONSTRAINT는 IF NOT EXISTS를 지원하지 않아(Postgres 제약), 먼저 지우고
-- 다시 걸어야 이 파일 전체를 처음부터 다시 실행해도 안전하다(파일의 다른
-- 모든 문장은 CREATE ... IF NOT EXISTS/DROP ... IF EXISTS로 이미 재실행 가능함).
ALTER TABLE public."COMMUNITY_POST" DROP CONSTRAINT IF EXISTS "community_post_accepted_comment_fk";
ALTER TABLE public."COMMUNITY_POST"
  ADD CONSTRAINT "community_post_accepted_comment_fk"
  FOREIGN KEY ("ACCEPTED_COMMENT_ID") REFERENCES public."COMMUNITY_COMMENT"("COMMENT_ID") ON DELETE SET NULL;

-- 채택 답변 검증: QnA 글에서만, 그 글에 달린 "최상위 답변"만(대댓글 채택 불가)
-- 채택할 수 있다. COMMUNITY_POST UPDATE RLS가 이미 글쓴이 본인만 통과시키므로
-- "질문자만 채택 가능"은 RLS가 보장하고, 이 트리거는 값 자체의 유효성만 본다
-- (notice_pin_limit_reached와 같은 BEFORE UPDATE 검증 트리거 패턴).
CREATE OR REPLACE FUNCTION public.enforce_community_accept_answer() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW."ACCEPTED_COMMENT_ID" IS NOT NULL AND NEW."ACCEPTED_COMMENT_ID" IS DISTINCT FROM OLD."ACCEPTED_COMMENT_ID" THEN
    IF NEW."CATEGORY" <> 'QNA' THEN
      RAISE EXCEPTION 'community_accept_not_qna' USING ERRCODE = 'P0001';
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM public."COMMUNITY_COMMENT" c
      WHERE c."COMMENT_ID" = NEW."ACCEPTED_COMMENT_ID"
        AND c."POST_ID" = NEW."POST_ID"
        AND c."PARENT_COMMENT_ID" IS NULL
    ) THEN
      RAISE EXCEPTION 'community_accept_invalid_answer' USING ERRCODE = 'P0001';
    END IF;
  END IF;
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_community_accept_answer ON public."COMMUNITY_POST";
CREATE TRIGGER trg_community_accept_answer BEFORE UPDATE ON public."COMMUNITY_POST"
  FOR EACH ROW EXECUTE FUNCTION public.enforce_community_accept_answer();

-- ── 댓글/답변 좋아요 ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public."COMMUNITY_COMMENT_LIKE" (
    "LIKE_ID"    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "COMMENT_ID" bigint NOT NULL REFERENCES public."COMMUNITY_COMMENT"("COMMENT_ID") ON DELETE CASCADE,
    "USER_ID"    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "CREATED_AT" timestamp with time zone DEFAULT now(),
    CONSTRAINT "community_comment_like_unique" UNIQUE ("COMMENT_ID", "USER_ID")
);
CREATE INDEX IF NOT EXISTS "idx_community_comment_like_comment" ON public."COMMUNITY_COMMENT_LIKE" ("COMMENT_ID");

ALTER TABLE public."COMMUNITY_COMMENT_LIKE" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "community_comment_like_read_all"   ON public."COMMUNITY_COMMENT_LIKE";
DROP POLICY IF EXISTS "community_comment_like_insert_own"  ON public."COMMUNITY_COMMENT_LIKE";
DROP POLICY IF EXISTS "community_comment_like_delete_own"  ON public."COMMUNITY_COMMENT_LIKE";
CREATE POLICY "community_comment_like_read_all" ON public."COMMUNITY_COMMENT_LIKE" FOR SELECT USING (true);
CREATE POLICY "community_comment_like_insert_own" ON public."COMMUNITY_COMMENT_LIKE" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = "USER_ID");
CREATE POLICY "community_comment_like_delete_own" ON public."COMMUNITY_COMMENT_LIKE" FOR DELETE TO authenticated
  USING ((select auth.uid()) = "USER_ID");

-- ── 신고 (게시글 / 댓글·답변) — SPIN_LOG_REPORT와 동일 패턴 ──────────────

CREATE TABLE IF NOT EXISTS public."COMMUNITY_POST_REPORT" (
    "REPORT_ID"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "POST_ID"     bigint NOT NULL REFERENCES public."COMMUNITY_POST"("POST_ID") ON DELETE CASCADE,
    "REPORTER_ID" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "REASON"      text CHECK (char_length("REASON") <= 300),
    "CREATED_AT"  timestamp with time zone DEFAULT now(),
    CONSTRAINT "community_post_report_unique" UNIQUE ("POST_ID", "REPORTER_ID")
);
ALTER TABLE public."COMMUNITY_POST_REPORT" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "community_post_report_select" ON public."COMMUNITY_POST_REPORT";
DROP POLICY IF EXISTS "community_post_report_insert" ON public."COMMUNITY_POST_REPORT";
CREATE POLICY "community_post_report_select" ON public."COMMUNITY_POST_REPORT" FOR SELECT TO authenticated
  USING (
    (select auth.uid()) = "REPORTER_ID"
    OR (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );
CREATE POLICY "community_post_report_insert" ON public."COMMUNITY_POST_REPORT" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = "REPORTER_ID");

CREATE TABLE IF NOT EXISTS public."COMMUNITY_COMMENT_REPORT" (
    "REPORT_ID"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "COMMENT_ID"  bigint NOT NULL REFERENCES public."COMMUNITY_COMMENT"("COMMENT_ID") ON DELETE CASCADE,
    "REPORTER_ID" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "REASON"      text CHECK (char_length("REASON") <= 300),
    "CREATED_AT"  timestamp with time zone DEFAULT now(),
    CONSTRAINT "community_comment_report_unique" UNIQUE ("COMMENT_ID", "REPORTER_ID")
);
ALTER TABLE public."COMMUNITY_COMMENT_REPORT" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "community_comment_report_select" ON public."COMMUNITY_COMMENT_REPORT";
DROP POLICY IF EXISTS "community_comment_report_insert" ON public."COMMUNITY_COMMENT_REPORT";
CREATE POLICY "community_comment_report_select" ON public."COMMUNITY_COMMENT_REPORT" FOR SELECT TO authenticated
  USING (
    (select auth.uid()) = "REPORTER_ID"
    OR (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );
CREATE POLICY "community_comment_report_insert" ON public."COMMUNITY_COMMENT_REPORT" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = "REPORTER_ID");

-- ── 조회수 — NOTICE와 동일하게 클라이언트 UPDATE 정책 없이 RPC로만 증가 ──

CREATE OR REPLACE FUNCTION public.increment_community_post_view_count(p_post_id bigint)
RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  UPDATE public."COMMUNITY_POST" SET "VIEW_COUNT" = "VIEW_COUNT" + 1 WHERE "POST_ID" = p_post_id;
$$;
REVOKE ALL ON FUNCTION public.increment_community_post_view_count(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.increment_community_post_view_count(bigint) TO authenticated, anon;

-- ── 게시글 첨부 이미지 스토리지 버킷 (사진만, 영상 없음 — notice-media와 달리
-- 유저가 직접 올리므로 유저별 경로로 네임스페이스, spin-log-media와 동일 패턴) ──

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'community-post-media', 'community-post-media', true, 10485760,
  ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp']
)
ON CONFLICT (id) DO UPDATE SET
  public = true,
  file_size_limit = 10485760,
  allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp'];

DROP POLICY IF EXISTS "community_post_media_read_all" ON storage.objects;
CREATE POLICY "community_post_media_read_all" ON storage.objects FOR SELECT
  USING (bucket_id = 'community-post-media');
-- 쓰기 정책 없음 — /api/community-post/upload가 (본인 인증 후) service role로만 업로드.
