-- 공지사항 (2026-07-15)
-- Run this whole file manually in the Supabase SQL Editor.
--
-- 관리자 전용 게시판. 이미지/영상을 여러 개 첨부할 수 있고(MEDIA_ITEMS jsonb
-- 배열), 최대 5개까지 상단 고정할 수 있다. 댓글 기능은 아예 만들지 않는다
-- (댓글 테이블 없음). 글이 등록되면 트리거가 모든 유저에게 NOTIFICATION을
-- 하나씩 뿌린다. 쓰기(작성/수정/삭제)는 /api/admin/notices 서버 라우트가
-- requireAdmin으로 검증한 뒤 service role로만 수행 — 클라이언트 INSERT/
-- UPDATE/DELETE 정책은 두지 않는다(VINYL_STORY와 동일한 패턴).

CREATE TABLE IF NOT EXISTS public."NOTICE" (
    "NOTICE_ID"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TITLE"       text NOT NULL,
    "CONTENT"     text NOT NULL,
    -- [{ "url": "https://...", "type": "image" | "video" }, ...] — 순서가 표시 순서
    "MEDIA_ITEMS" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "IS_PINNED"   boolean NOT NULL DEFAULT false,
    "PINNED_AT"   timestamp with time zone,
    "AUTHOR_ID"   uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    "CREATED_AT"  timestamp with time zone DEFAULT now(),
    "UPDATED_AT"  timestamp with time zone DEFAULT now(),
    CONSTRAINT "notice_media_items_is_array" CHECK (jsonb_typeof("MEDIA_ITEMS") = 'array'),
    CONSTRAINT "notice_media_items_max_10" CHECK (jsonb_array_length("MEDIA_ITEMS") <= 10)
);

CREATE INDEX IF NOT EXISTS "idx_notice_pinned"  ON public."NOTICE" ("IS_PINNED", "PINNED_AT" DESC);
CREATE INDEX IF NOT EXISTS "idx_notice_created" ON public."NOTICE" ("CREATED_AT" DESC);

ALTER TABLE public."NOTICE" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "notice_read_all" ON public."NOTICE";
CREATE POLICY "notice_read_all" ON public."NOTICE" FOR SELECT USING (true);
-- client INSERT/UPDATE/DELETE 정책 없음 — /api/admin/notices만 service role로 기록.

-- 상단 고정 최대 5개 강제 + PINNED_AT 자동 관리(고정 해제 시 NULL, 고정 시
-- now() — PINNED_AT DESC 정렬로 "최근에 고정한 것"이 위로 온다).
CREATE OR REPLACE FUNCTION public.enforce_notice_pin_limit() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE v_count int;
BEGIN
  IF NEW."IS_PINNED" = true THEN
    IF NEW."PINNED_AT" IS NULL THEN
      NEW."PINNED_AT" := now();
    END IF;
    IF TG_OP = 'INSERT' OR OLD."IS_PINNED" IS DISTINCT FROM true THEN
      SELECT count(*) INTO v_count FROM public."NOTICE"
        WHERE "IS_PINNED" = true AND "NOTICE_ID" IS DISTINCT FROM NEW."NOTICE_ID";
      IF v_count >= 5 THEN
        RAISE EXCEPTION 'notice_pin_limit_reached' USING ERRCODE = 'P0001';
      END IF;
    END IF;
  ELSE
    NEW."PINNED_AT" := NULL;
  END IF;
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_notice_pin_limit ON public."NOTICE";
CREATE TRIGGER trg_notice_pin_limit BEFORE INSERT OR UPDATE ON public."NOTICE"
  FOR EACH ROW EXECUTE FUNCTION public.enforce_notice_pin_limit();

-- notice-media 스토리지 버킷 (없으면 생성, 공개 read). MIME 화이트리스트와
-- 용량 상한은 /api/admin/notices/upload의 앱 레벨 검사와 동일한 값을
-- 버킷에도 걸어 이중 방어한다(spin-log-media 버킷과 같은 패턴).
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'notice-media', 'notice-media', true, 52428800,
  ARRAY['image/jpeg','image/png','image/gif','image/webp','video/mp4','video/quicktime']
)
ON CONFLICT (id) DO UPDATE SET
  public = true,
  file_size_limit = 52428800,
  allowed_mime_types = ARRAY['image/jpeg','image/png','image/gif','image/webp','video/mp4','video/quicktime'];

DROP POLICY IF EXISTS "notice_media_read_all" ON storage.objects;
CREATE POLICY "notice_media_read_all" ON storage.objects FOR SELECT
  USING (bucket_id = 'notice-media');
-- 쓰기 정책 없음 — /api/admin/notices/upload가 service role로만 업로드.

-- ── NOTIFICATION 연동: 공지 알림 타입 추가 + 모든 유저에게 팬아웃 ──

ALTER TABLE public."NOTIFICATION"
  ADD COLUMN IF NOT EXISTS "NOTICE_ID" bigint REFERENCES public."NOTICE"("NOTICE_ID") ON DELETE CASCADE;

-- NOTIFICATION.TYPE의 CHECK 제약은 원래 테이블 생성 시 인라인으로 걸려
-- 이름이 자동 부여됐다 — 정확한 이름을 몰라도 안전하게 교체할 수 있도록
-- 동적으로 찾아서 지운다.
DO $$
DECLARE con_name text;
BEGIN
  SELECT con.conname INTO con_name
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
  WHERE nsp.nspname = 'public'
    AND rel.relname = 'NOTIFICATION'
    AND con.contype = 'c'
    AND pg_get_constraintdef(con.oid) ILIKE '%"TYPE"%';
  IF con_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public."NOTIFICATION" DROP CONSTRAINT %I', con_name);
  END IF;
END $$;

ALTER TABLE public."NOTIFICATION" ADD CONSTRAINT "notification_type_check"
  CHECK ("TYPE" IN (
    'SPIN_LIKE','SPIN_COMMENT','SPIN_REPLY',
    'VINYL_LIKE','VINYL_COMMENT','VINYL_REPLY',
    'FOLLOW_REQUEST','FOLLOW_ACCEPTED','NEW_FOLLOWER',
    'NOTICE'));

-- 공지 등록 시 전체 유저에게 알림 팬아웃(단건 INSERT...SELECT, 유저 수가
-- 많아도 한 번의 SQL로 처리된다). 수정 시에는 재알림하지 않는다(AFTER
-- INSERT만). ACTOR_ID는 NULL — "누가" 보다 "시스템 공지"라는 성격이 강하다.
CREATE OR REPLACE FUNCTION public.notify_all_users_new_notice() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public."NOTIFICATION" ("USER_ID","ACTOR_ID","TYPE","NOTICE_ID")
  SELECT id, NULL, 'NOTICE', NEW."NOTICE_ID" FROM auth.users;
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_notify_new_notice ON public."NOTICE";
CREATE TRIGGER trg_notify_new_notice AFTER INSERT ON public."NOTICE"
  FOR EACH ROW EXECUTE FUNCTION public.notify_all_users_new_notice();
