-- 공지사항 댓글 + 댓글 좋아요 (2026-07-15)
-- Run this whole file manually in the Supabase SQL Editor.
-- supabase_schema_migration_notice.sql이 먼저 실행돼 있어야 한다(NOTICE 테이블 필요).
--
-- 최초 설계는 "공지는 댓글 없음"이었으나, 댓글 + 댓글 좋아요 + 관리자의
-- 공지별 댓글 열기/닫기 토글로 요구사항이 바뀌었다. IS_COMMENTS_ENABLED는
-- 새 공지의 기본값을 true로 두고(댓글 가능), 관리자가 글 작성/수정 시 언제든
-- 끄고 켤 수 있다. 댓글 삭제는 작성자 본인 또는 관리자만 — 답글 스레딩은
-- 요청 범위 밖이라 만들지 않는다(플랫 목록).

ALTER TABLE public."NOTICE"
  ADD COLUMN IF NOT EXISTS "IS_COMMENTS_ENABLED" boolean NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS public."NOTICE_COMMENT" (
    "COMMENT_ID"  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NOTICE_ID"   bigint NOT NULL REFERENCES public."NOTICE"("NOTICE_ID") ON DELETE CASCADE,
    "USER_ID"     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "CONTENT"     text NOT NULL,
    "CREATED_AT"  timestamp with time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_notice_comment_notice" ON public."NOTICE_COMMENT" ("NOTICE_ID", "CREATED_AT");

ALTER TABLE public."NOTICE_COMMENT" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "notice_comment_read_all"    ON public."NOTICE_COMMENT";
DROP POLICY IF EXISTS "notice_comment_insert_own"   ON public."NOTICE_COMMENT";
DROP POLICY IF EXISTS "notice_comment_delete_own_or_admin" ON public."NOTICE_COMMENT";
CREATE POLICY "notice_comment_read_all" ON public."NOTICE_COMMENT" FOR SELECT USING (true);
-- 공지 자체가 댓글을 막아두면(IS_COMMENTS_ENABLED=false) INSERT 자체가 거부된다
-- — 관리자가 UI에서 입력창을 숨기는 것과 별개로 서버 단에서도 강제.
CREATE POLICY "notice_comment_insert_own" ON public."NOTICE_COMMENT" FOR INSERT TO authenticated
  WITH CHECK (
    (select auth.uid()) = "USER_ID"
    AND EXISTS (
      SELECT 1 FROM public."NOTICE" n
      WHERE n."NOTICE_ID" = "NOTICE_ID" AND n."IS_COMMENTS_ENABLED" = true
    )
  );
CREATE POLICY "notice_comment_delete_own_or_admin" ON public."NOTICE_COMMENT" FOR DELETE TO authenticated
  USING (
    (select auth.uid()) = "USER_ID"
    OR (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

CREATE TABLE IF NOT EXISTS public."NOTICE_COMMENT_LIKE" (
    "LIKE_ID"     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "COMMENT_ID"  bigint NOT NULL REFERENCES public."NOTICE_COMMENT"("COMMENT_ID") ON DELETE CASCADE,
    "USER_ID"     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "CREATED_AT"  timestamp with time zone DEFAULT now(),
    CONSTRAINT "notice_comment_like_unique" UNIQUE ("COMMENT_ID", "USER_ID")
);
CREATE INDEX IF NOT EXISTS "idx_notice_comment_like_comment" ON public."NOTICE_COMMENT_LIKE" ("COMMENT_ID");

ALTER TABLE public."NOTICE_COMMENT_LIKE" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "notice_comment_like_read_all"  ON public."NOTICE_COMMENT_LIKE";
DROP POLICY IF EXISTS "notice_comment_like_insert_own" ON public."NOTICE_COMMENT_LIKE";
DROP POLICY IF EXISTS "notice_comment_like_delete_own" ON public."NOTICE_COMMENT_LIKE";
CREATE POLICY "notice_comment_like_read_all" ON public."NOTICE_COMMENT_LIKE" FOR SELECT USING (true);
CREATE POLICY "notice_comment_like_insert_own" ON public."NOTICE_COMMENT_LIKE" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = "USER_ID");
CREATE POLICY "notice_comment_like_delete_own" ON public."NOTICE_COMMENT_LIKE" FOR DELETE TO authenticated
  USING ((select auth.uid()) = "USER_ID");
