-- Create ALBUM_MASTER Table
CREATE TABLE public."ALBUM_MASTER" (
    "ALBUM_ID" bigint PRIMARY KEY,
    "TITLE" text NOT NULL,
    "ARTIST" text NOT NULL,
    "RELEASE_YEAR" integer,
    "IMAGE_URL" text,
    "VINYL_IMAGE_URL" text,
    "CUSTOM_COLOR_HEX" text,
    "CUSTOM_STYLE_TYPE" text,
    "TRACKS" jsonb
);

-- Create USER_VINYL Table
CREATE TABLE public."USER_VINYL" (
    "USER_VINYL_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "USER_ID" uuid NOT NULL,
    "ALBUM_ID" bigint NOT NULL REFERENCES public."ALBUM_MASTER"("ALBUM_ID"),
    "STATUS" text NOT NULL,
    "PURCHASE_DATE" timestamp with time zone,
    "PURCHASE_PRICE" integer,
    "ADDED_AT" timestamp with time zone DEFAULT now()
);

-- Create VINYL_TAG Table
CREATE TABLE public."VINYL_TAG" (
    "TAG_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ALBUM_ID" bigint NOT NULL REFERENCES public."ALBUM_MASTER"("ALBUM_ID"),
    "TAG_TYPE" text,
    "TAG_NAME" text NOT NULL,
    CONSTRAINT "vinyl_tag_album_name_key" UNIQUE ("ALBUM_ID", "TAG_NAME")
);

-- Enable Supabase Realtime for the USER_VINYL table
-- This allows our apps to receive instant updates when a vinyl is added or modified
ALTER PUBLICATION supabase_realtime ADD TABLE public."USER_VINYL";

-- Add MARKET_PRICE column to ALBUM_MASTER Table
-- Run this manually in the Supabase SQL Editor: the column was missing, which
-- caused createAlbumMaster() to strip MARKET_PRICE from every save (PGRST204).
ALTER TABLE public."ALBUM_MASTER" ADD COLUMN IF NOT EXISTS "MARKET_PRICE" integer;

-- ============================================================
-- Row Level Security (RLS)
-- Run this manually in the Supabase SQL Editor.
--
-- Access model:
--   * Anyone (including logged-out visitors) can READ everything —
--     public dashboards (/user/[id]) must render collections for
--     non-members.
--   * Only authenticated users can WRITE, and USER_VINYL/PROFILES
--     rows can only be written by their owner (auth.uid()).
--   * ALBUM_MASTER/VINYL_TAG are shared master data: any signed-in
--     user may insert/update (scan & search flows create these),
--     but anonymous clients may not.
-- ============================================================

-- ALBUM_MASTER: public read / authenticated insert / no update or delete
ALTER TABLE public."ALBUM_MASTER" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "album_master_read_all"    ON public."ALBUM_MASTER";
DROP POLICY IF EXISTS "album_master_insert_auth" ON public."ALBUM_MASTER";
DROP POLICY IF EXISTS "album_master_update_auth" ON public."ALBUM_MASTER";
CREATE POLICY "album_master_read_all"    ON public."ALBUM_MASTER" FOR SELECT USING (true);
CREATE POLICY "album_master_insert_auth" ON public."ALBUM_MASTER" FOR INSERT TO authenticated WITH CHECK (true);
-- Update is deliberately disabled to prevent malicious overwrites of shared data

-- VINYL_TAG: public read / authenticated insert / no delete
ALTER TABLE public."VINYL_TAG" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "vinyl_tag_read_all"    ON public."VINYL_TAG";
DROP POLICY IF EXISTS "vinyl_tag_insert_auth" ON public."VINYL_TAG";
DROP POLICY IF EXISTS "vinyl_tag_delete_auth" ON public."VINYL_TAG";
CREATE POLICY "vinyl_tag_read_all"    ON public."VINYL_TAG" FOR SELECT USING (true);
CREATE POLICY "vinyl_tag_insert_auth" ON public."VINYL_TAG" FOR INSERT TO authenticated WITH CHECK (true);
-- Delete is deliberately disabled to prevent malicious removal of tags

-- USER_VINYL: public read / owner-only write
ALTER TABLE public."USER_VINYL" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "user_vinyl_read_all"     ON public."USER_VINYL";
DROP POLICY IF EXISTS "user_vinyl_insert_own"   ON public."USER_VINYL";
DROP POLICY IF EXISTS "user_vinyl_update_own"   ON public."USER_VINYL";
DROP POLICY IF EXISTS "user_vinyl_delete_own"   ON public."USER_VINYL";
CREATE POLICY "user_vinyl_read_all"   ON public."USER_VINYL" FOR SELECT USING (true);
CREATE POLICY "user_vinyl_insert_own" ON public."USER_VINYL" FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = "USER_ID");
CREATE POLICY "user_vinyl_update_own" ON public."USER_VINYL" FOR UPDATE TO authenticated
  USING (auth.uid() = "USER_ID")
  WITH CHECK (auth.uid() = "USER_ID");
CREATE POLICY "user_vinyl_delete_own" ON public."USER_VINYL" FOR DELETE TO authenticated
  USING (auth.uid() = "USER_ID");

-- PROFILES: public read (nickname display) / owner-only write
ALTER TABLE public."PROFILES" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "profiles_read_all"   ON public."PROFILES";
DROP POLICY IF EXISTS "profiles_insert_own" ON public."PROFILES";
DROP POLICY IF EXISTS "profiles_update_own" ON public."PROFILES";
CREATE POLICY "profiles_read_all"   ON public."PROFILES" FOR SELECT USING (true);
CREATE POLICY "profiles_insert_own" ON public."PROFILES" FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = "USER_ID");
CREATE POLICY "profiles_update_own" ON public."PROFILES" FOR UPDATE TO authenticated
  USING (auth.uid() = "USER_ID")
  WITH CHECK (auth.uid() = "USER_ID");

-- ============================================================
-- Admin & Support system (INQUIRY / INQUIRY_REPLY / EVENT_LOG)
-- Run this manually in the Supabase SQL Editor.
--
-- Access model:
--   * INQUIRY / INQUIRY_REPLY: owner-only read & insert. Admin access
--     goes through service-role API routes (bypasses RLS), so no
--     admin policies are needed here.
--   * EVENT_LOG: authenticated insert-only (own USER_ID). No SELECT
--     policy at all — only the service-role server can read it.
-- ============================================================

CREATE TABLE IF NOT EXISTS public."INQUIRY" (
    "INQUIRY_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "USER_ID"    uuid NOT NULL,
    "CATEGORY"   text NOT NULL DEFAULT 'GENERAL',  -- COMPLAINT | SUGGESTION | BUG | GENERAL
    "TITLE"      text NOT NULL,
    "CONTENT"    text NOT NULL,
    "STATUS"     text NOT NULL DEFAULT 'OPEN',     -- OPEN | ANSWERED | CLOSED
    "PLATFORM"   text NOT NULL DEFAULT 'WEB',      -- WEB | MOBILE
    "ATTACHMENTS" jsonb,                           -- [{url,type:'image'|'video',name}] — inquiry-attachments 버킷 공개 URL
    "CREATED_AT" timestamp with time zone DEFAULT now(),
    "UPDATED_AT" timestamp with time zone DEFAULT now()
);

-- 2026-07-13: 문의 첨부(이미지/GIF/영상) — 기존 테이블에는 이 한 줄만 실행
ALTER TABLE public."INQUIRY" ADD COLUMN IF NOT EXISTS "ATTACHMENTS" jsonb;

-- 2026-07-13: 유저 촬영 재킷 커버 — 에디션별 실물 재킷이 마스터 커버와 다를 때
-- 본인 보관함에서만 우선 표시되는 커버 URL (user-covers 버킷, 업로드는
-- /api/user-cover/upload 서버 라우트가 인증 검증 후 service role로 수행)
ALTER TABLE public."USER_VINYL" ADD COLUMN IF NOT EXISTS "CUSTOM_IMAGE_URL" text;

-- 2026-07-13: '기존 커버' 영구 백업 — 유저 촬영본이 IMAGE_URL을 덮어쓸 때
-- (/api/album-master/cover) 서버가 직전 카탈로그 커버를 여기 백업하고,
-- '기존 커버로 되돌리기'가 이 값으로 복원한다. 세션 메모리에만 원본을 들고
-- 있다가 전체 공개 후 복원이 불가능해지던 결함의 수정.
ALTER TABLE public."ALBUM_MASTER" ADD COLUMN IF NOT EXISTS "ORIGINAL_IMAGE_URL" text;
-- 첨부 파일 저장소: inquiry-attachments 버킷은 서비스가 API로 생성/업로드
-- (public read, 50MB 제한, 이미지/영상 MIME 화이트리스트; 업로드는
-- /api/support/upload 서버 라우트가 인증 검증 후 service role로 수행)

CREATE TABLE IF NOT EXISTS public."INQUIRY_REPLY" (
    "REPLY_ID"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "INQUIRY_ID" bigint NOT NULL REFERENCES public."INQUIRY"("INQUIRY_ID") ON DELETE CASCADE,
    "USER_ID"    uuid,
    "IS_ADMIN"   boolean NOT NULL DEFAULT false,
    "CONTENT"    text NOT NULL,
    "CREATED_AT" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."EVENT_LOG" (
    "EVENT_ID"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EVENT_TYPE" text NOT NULL,                    -- LOGIN | SEARCH | SCAN | ALBUM_ADD | WISH_ADD | SHARE
    "USER_ID"    uuid,
    "PLATFORM"   text NOT NULL DEFAULT 'WEB',      -- WEB | MOBILE
    "META"       jsonb,
    "CREATED_AT" timestamp with time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "idx_event_log_type_created" ON public."EVENT_LOG" ("EVENT_TYPE", "CREATED_AT");
CREATE INDEX IF NOT EXISTS "idx_event_log_created"      ON public."EVENT_LOG" ("CREATED_AT");
CREATE INDEX IF NOT EXISTS "idx_inquiry_user_created"   ON public."INQUIRY" ("USER_ID", "CREATED_AT" DESC);
CREATE INDEX IF NOT EXISTS "idx_inquiry_reply_parent"   ON public."INQUIRY_REPLY" ("INQUIRY_ID");

-- INQUIRY: owner-only read / owner-only insert / no client update-delete
ALTER TABLE public."INQUIRY" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "inquiry_select_own" ON public."INQUIRY";
DROP POLICY IF EXISTS "inquiry_insert_own" ON public."INQUIRY";
CREATE POLICY "inquiry_select_own" ON public."INQUIRY" FOR SELECT TO authenticated
  USING ((select auth.uid()) = "USER_ID");
CREATE POLICY "inquiry_insert_own" ON public."INQUIRY" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = "USER_ID" AND "STATUS" = 'OPEN');

-- INQUIRY_REPLY: readable by the inquiry owner; users can only add their
-- own non-admin replies (IS_ADMIN can't be forged from the client)
ALTER TABLE public."INQUIRY_REPLY" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "inquiry_reply_select_own" ON public."INQUIRY_REPLY";
DROP POLICY IF EXISTS "inquiry_reply_insert_own" ON public."INQUIRY_REPLY";
CREATE POLICY "inquiry_reply_select_own" ON public."INQUIRY_REPLY" FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public."INQUIRY" i
                 WHERE i."INQUIRY_ID" = "INQUIRY_REPLY"."INQUIRY_ID"
                   AND i."USER_ID" = (select auth.uid())));
CREATE POLICY "inquiry_reply_insert_own" ON public."INQUIRY_REPLY" FOR INSERT TO authenticated
  WITH CHECK ("IS_ADMIN" = false AND (select auth.uid()) = "USER_ID"
              AND EXISTS (SELECT 1 FROM public."INQUIRY" i
                          WHERE i."INQUIRY_ID" = "INQUIRY_REPLY"."INQUIRY_ID"
                            AND i."USER_ID" = (select auth.uid())));

-- EVENT_LOG: authenticated insert-only (own rows), intentionally NO select
-- policy — analytics reads happen exclusively through service-role routes
ALTER TABLE public."EVENT_LOG" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "event_log_insert_own" ON public."EVENT_LOG";
CREATE POLICY "event_log_insert_own" ON public."EVENT_LOG" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = "USER_ID");

-- Grant admin role (run ONCE for your own account, then sign out & back in;
-- app_metadata is only writable with the service role, so users can't
-- self-promote — do NOT put the role in user_metadata)
-- UPDATE auth.users
--   SET raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb) || '{"role":"admin"}'
--   WHERE email = 'yjw127588@gmail.com';

-- ── Acquisition tracking: allow anonymous VISIT events ─────────
-- Landing/public-dashboard visits happen before login, so the anon role
-- may insert EVENT_LOG rows — but ONLY type VISIT with a null USER_ID
-- (prevents forging other users' activity). Run in the SQL Editor.
DROP POLICY IF EXISTS "event_log_insert_visit_anon" ON public."EVENT_LOG";
CREATE POLICY "event_log_insert_visit_anon" ON public."EVENT_LOG" FOR INSERT TO anon
  WITH CHECK ("EVENT_TYPE" = 'VISIT' AND "USER_ID" IS NULL);

-- ============================================================
-- Hardening migration (2026-07-11)
-- Run this whole section manually in the Supabase SQL Editor.
--
-- Fixes found in the security audit:
--   1. PROFILES had no DDL in this file (dashboard-only) → codified.
--   2. Nickname 30-day cooldown was client-side only → DB trigger.
--   3. Logged-in visits were dropped by RLS (insert_own requires
--      USER_ID = auth.uid(), but VISIT rows carry NULL) → new policy.
--   4. EVENT_LOG accepted any EVENT_TYPE / unbounded META from any
--      authenticated user → CHECK constraints + anon flood brake.
--   5. USER_VINYL allowed duplicate (user, album) rows, had no index
--      on USER_ID, no FK to auth.users, no STATUS/price validation.
--   6. INQUIRY enum values existed only as comments → CHECKs; user
--      replies now reopen the inquiry and bump UPDATED_AT.
--   7. avatars bucket policies lived only in the dashboard → codified
--      (uploads now go to a per-user folder: {uid}/avatar-*.ext).
-- ============================================================

-- 1. PROFILES table (previously created via dashboard only)
CREATE TABLE IF NOT EXISTS public."PROFILES" (
    "USER_ID" uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    "DISPLAY_NAME" text UNIQUE,
    "LAST_NAME_CHANGED_AT" timestamp with time zone
);

-- 2. Nickname cooldown enforced in the DB. The trigger also owns
--    LAST_NAME_CHANGED_AT so clients can't backdate it via PostgREST.
CREATE OR REPLACE FUNCTION public.enforce_nickname_cooldown()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW."LAST_NAME_CHANGED_AT" := now();
  ELSIF NEW."DISPLAY_NAME" IS DISTINCT FROM OLD."DISPLAY_NAME" THEN
    IF OLD."LAST_NAME_CHANGED_AT" IS NOT NULL
       AND OLD."LAST_NAME_CHANGED_AT" > now() - interval '30 days' THEN
      RAISE EXCEPTION '닉네임은 30일에 한 번만 변경 가능합니다.'
        USING ERRCODE = 'P0001';
    END IF;
    NEW."LAST_NAME_CHANGED_AT" := now();
  ELSE
    NEW."LAST_NAME_CHANGED_AT" := OLD."LAST_NAME_CHANGED_AT";
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_nickname_cooldown ON public."PROFILES";
CREATE TRIGGER trg_nickname_cooldown
  BEFORE INSERT OR UPDATE ON public."PROFILES"
  FOR EACH ROW EXECUTE FUNCTION public.enforce_nickname_cooldown();

-- 3. Logged-in sessions also record VISIT rows with USER_ID NULL
--    (events.ts nulls it for VISIT), which event_log_insert_own rejected.
DROP POLICY IF EXISTS "event_log_insert_visit_auth" ON public."EVENT_LOG";
CREATE POLICY "event_log_insert_visit_auth" ON public."EVENT_LOG" FOR INSERT TO authenticated
  WITH CHECK ("EVENT_TYPE" = 'VISIT' AND "USER_ID" IS NULL);

-- 4a. EVENT_LOG value/size validation (NOT VALID: applies to new rows only,
--     so it can't fail on pre-existing data)
ALTER TABLE public."EVENT_LOG" DROP CONSTRAINT IF EXISTS "event_log_type_check";
ALTER TABLE public."EVENT_LOG" ADD CONSTRAINT "event_log_type_check"
  CHECK ("EVENT_TYPE" IN ('VISIT','SIGNUP','LOGIN','SEARCH','SCAN','ALBUM_ADD','WISH_ADD','SHARE')) NOT VALID;
ALTER TABLE public."EVENT_LOG" DROP CONSTRAINT IF EXISTS "event_log_meta_size_check";
ALTER TABLE public."EVENT_LOG" ADD CONSTRAINT "event_log_meta_size_check"
  CHECK ("META" IS NULL OR pg_column_size("META") < 4096) NOT VALID;

-- 4b. Flood brake: the anon key is public, so a curl loop could insert
--     unlimited VISIT rows (storage cost + poisoned acquisition metrics).
--     Hard-cap anonymous VISIT inserts at 120/min globally — legit traffic
--     never hits this, a spam loop stops doing damage after one minute.
--     (Uses idx_event_log_type_created, so the count is an index-only scan.)
CREATE OR REPLACE FUNCTION public.event_log_flood_brake()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW."EVENT_TYPE" = 'VISIT' AND NEW."USER_ID" IS NULL THEN
    IF (SELECT count(*) FROM public."EVENT_LOG"
        WHERE "EVENT_TYPE" = 'VISIT'
          AND "CREATED_AT" > now() - interval '1 minute') >= 120 THEN
      RAISE EXCEPTION 'VISIT rate limit exceeded' USING ERRCODE = 'P0002';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_event_log_flood_brake ON public."EVENT_LOG";
CREATE TRIGGER trg_event_log_flood_brake
  BEFORE INSERT ON public."EVENT_LOG"
  FOR EACH ROW EXECUTE FUNCTION public.event_log_flood_brake();

-- 5. USER_VINYL integrity: dedupe, then one row per (user, album),
--    index for the hot USER_ID lookups, FK cleanup on account deletion,
--    and STATUS/price validation.
DELETE FROM public."USER_VINYL" a
  USING public."USER_VINYL" b
  WHERE a."USER_VINYL_ID" > b."USER_VINYL_ID"
    AND a."USER_ID" = b."USER_ID"
    AND a."ALBUM_ID" = b."ALBUM_ID";
ALTER TABLE public."USER_VINYL" DROP CONSTRAINT IF EXISTS "user_vinyl_user_album_key";
ALTER TABLE public."USER_VINYL" ADD CONSTRAINT "user_vinyl_user_album_key"
  UNIQUE ("USER_ID", "ALBUM_ID");
CREATE INDEX IF NOT EXISTS "idx_user_vinyl_user" ON public."USER_VINYL" ("USER_ID");
DELETE FROM public."USER_VINYL" uv
  WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = uv."USER_ID");
ALTER TABLE public."USER_VINYL" DROP CONSTRAINT IF EXISTS "user_vinyl_user_fk";
ALTER TABLE public."USER_VINYL" ADD CONSTRAINT "user_vinyl_user_fk"
  FOREIGN KEY ("USER_ID") REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."USER_VINYL" DROP CONSTRAINT IF EXISTS "user_vinyl_status_check";
ALTER TABLE public."USER_VINYL" ADD CONSTRAINT "user_vinyl_status_check"
  CHECK ("STATUS" IN ('OWNED','WISH')) NOT VALID;
ALTER TABLE public."USER_VINYL" DROP CONSTRAINT IF EXISTS "user_vinyl_price_check";
ALTER TABLE public."USER_VINYL" ADD CONSTRAINT "user_vinyl_price_check"
  CHECK ("PURCHASE_PRICE" IS NULL OR ("PURCHASE_PRICE" >= 0 AND "PURCHASE_PRICE" <= 100000000)) NOT VALID;

-- 6a. INQUIRY enum comments promoted to real constraints
ALTER TABLE public."INQUIRY" DROP CONSTRAINT IF EXISTS "inquiry_category_check";
ALTER TABLE public."INQUIRY" ADD CONSTRAINT "inquiry_category_check"
  CHECK ("CATEGORY" IN ('COMPLAINT','SUGGESTION','BUG','GENERAL')) NOT VALID;
ALTER TABLE public."INQUIRY" DROP CONSTRAINT IF EXISTS "inquiry_status_check";
ALTER TABLE public."INQUIRY" ADD CONSTRAINT "inquiry_status_check"
  CHECK ("STATUS" IN ('OPEN','ANSWERED','CLOSED')) NOT VALID;
ALTER TABLE public."INQUIRY" DROP CONSTRAINT IF EXISTS "inquiry_platform_check";
ALTER TABLE public."INQUIRY" ADD CONSTRAINT "inquiry_platform_check"
  CHECK ("PLATFORM" IN ('WEB','MOBILE')) NOT VALID;

-- 6b. A user reply must reopen the inquiry and bump UPDATED_AT so the
--     admin sees the follow-up. Clients have no UPDATE policy on INQUIRY
--     (by design), so this runs as a SECURITY DEFINER trigger instead.
CREATE OR REPLACE FUNCTION public.on_inquiry_reply()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public."INQUIRY"
     SET "UPDATED_AT" = now(),
         "STATUS" = CASE WHEN NEW."IS_ADMIN" THEN "STATUS" ELSE 'OPEN' END
   WHERE "INQUIRY_ID" = NEW."INQUIRY_ID";
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_on_inquiry_reply ON public."INQUIRY_REPLY";
CREATE TRIGGER trg_on_inquiry_reply
  AFTER INSERT ON public."INQUIRY_REPLY"
  FOR EACH ROW EXECUTE FUNCTION public.on_inquiry_reply();

-- 7. avatars bucket: codified policies. App code now uploads to a
--    per-user folder ({uid}/avatar-{ts}.ext) so ownership is checkable.
--    Public read is intended (avatars render on public dashboards).
DROP POLICY IF EXISTS "avatar_read_all" ON storage.objects;
CREATE POLICY "avatar_read_all" ON storage.objects FOR SELECT
  USING (bucket_id = 'avatars');
DROP POLICY IF EXISTS "avatar_upload_own" ON storage.objects;
CREATE POLICY "avatar_upload_own" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text);
DROP POLICY IF EXISTS "avatar_delete_own" ON storage.objects;
CREATE POLICY "avatar_delete_own" ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text);

-- ============================================================
-- Founding member badge migration (2026-07-12)
-- Run this whole section manually in the Supabase SQL Editor.
--
-- Adds a permanent, DB-assigned signup number to PROFILES so a "first
-- 100 users" badge can't be spoofed. Every other badge is evaluated
-- client-side from the user's own collection stats and self-reported
-- via updateUnlockedBadges() with no server validation — fine for
-- vanity badges, not fine for something meant to be scarce/exclusive.
-- ============================================================

-- 1. One monotonically increasing number per profile, assigned once.
CREATE SEQUENCE IF NOT EXISTS public.profiles_signup_seq;
ALTER TABLE public."PROFILES" ADD COLUMN IF NOT EXISTS "SIGNUP_NUMBER" integer;

-- 2. Trigger owns SIGNUP_NUMBER (same pattern as enforce_nickname_cooldown
--    owning LAST_NAME_CHANGED_AT) — a client can UPDATE its own PROFILES
--    row under RLS, but can never move up the queue this way.
CREATE OR REPLACE FUNCTION public.assign_signup_number()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW."SIGNUP_NUMBER" := nextval('public.profiles_signup_seq');
  ELSIF OLD."SIGNUP_NUMBER" IS NOT NULL THEN
    -- Already assigned — immutable, ignore whatever the client sent.
    NEW."SIGNUP_NUMBER" := OLD."SIGNUP_NUMBER";
  END IF;
  -- else: OLD.SIGNUP_NUMBER IS NULL (not yet backfilled) — let NEW's
  -- value through. Only matters for step 3's one-time backfill UPDATE
  -- below; every row inserted after this migration gets its number at
  -- INSERT time, so OLD.SIGNUP_NUMBER is never NULL for it again.
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_assign_signup_number ON public."PROFILES";
CREATE TRIGGER trg_assign_signup_number
  BEFORE INSERT OR UPDATE ON public."PROFILES"
  FOR EACH ROW EXECUTE FUNCTION public.assign_signup_number();

-- 3. Some accounts (e.g. anyone whose displayName was already set before
--    this migration ever existed) never went through updateProfile()'s
--    "only upsert PROFILES when the name is changing" path, so they have
--    no PROFILES row at all and would be silently excluded from both the
--    badge and the backfill below. Create the missing rows from their
--    existing auth metadata. Trigger is off here since its INSERT branch
--    would otherwise force a fresh nextval() instead of leaving room for
--    step 4's full, order-correct renumber.
ALTER TABLE public."PROFILES" DISABLE TRIGGER trg_assign_signup_number;
INSERT INTO public."PROFILES" ("USER_ID", "DISPLAY_NAME")
SELECT u.id, u.raw_user_meta_data->>'displayName'
FROM auth.users u
LEFT JOIN public."PROFILES" p ON p."USER_ID" = u.id
WHERE p."USER_ID" IS NULL AND u.raw_user_meta_data->>'displayName' IS NOT NULL
ON CONFLICT ("USER_ID") DO NOTHING;

-- 4. Full (re-)number of every profile by real auth.users.created_at
--    (PROFILES has no CREATED_AT of its own, and LAST_NAME_CHANGED_AT
--    drifts forward if they ever changed their nickname). Safe to re-run.
WITH ordered AS (
  SELECT p."USER_ID", row_number() OVER (ORDER BY u.created_at) AS rn
  FROM public."PROFILES" p
  JOIN auth.users u ON u.id = p."USER_ID"
)
UPDATE public."PROFILES" p
SET "SIGNUP_NUMBER" = ordered.rn
FROM ordered
WHERE p."USER_ID" = ordered."USER_ID";
ALTER TABLE public."PROFILES" ENABLE TRIGGER trg_assign_signup_number;

-- 5. Point the sequence past the (re-)numbered rows so new signups
--    continue the count instead of colliding with it.
SELECT setval('public.profiles_signup_seq', GREATEST((SELECT count(*) FROM public."PROFILES"), 1));
-- ============================================================
-- Read Tracking Migration (2026-07-13)
-- Run this section manually in the Supabase SQL Editor.
--
-- This adds the columns required for the "edit inquiry" and "edit reply"
-- features.
-- 1. ADMIN_READ_AT on INQUIRY: Set when an admin opens the inquiry thread.
--    Users can edit their inquiries as long as this is null.
-- 2. READ_AT on INQUIRY_REPLY: Set when a user opens the inquiry thread.
--    Admins can edit their replies as long as this is null.
-- ============================================================

ALTER TABLE public."INQUIRY" ADD COLUMN IF NOT EXISTS "ADMIN_READ_AT" timestamp with time zone;
ALTER TABLE public."INQUIRY_REPLY" ADD COLUMN IF NOT EXISTS "READ_AT" timestamp with time zone;

-- ============================================================
-- Spinning Diary / Listening Log (2026-07-14)
-- Run this section manually in the Supabase SQL Editor.
--
-- 오늘 턴테이블에 올린 LP를 기록하는 "다이어리" 기능. USER_VINYL과 동일한
-- RLS 패턴(public read / owner-only write)을 따른다 — 컬렉션 자체가 이미
-- 전체 공개이므로 재생 기록을 공개하는 것도 새로운 프라이버시 노출이 아니며,
-- 이 테이블은 향후 디스커버리 피드의 데이터 소스로도 재사용된다.
-- ============================================================

CREATE TABLE IF NOT EXISTS public."LISTENING_LOG" (
    "LOG_ID"       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "USER_ID"      uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "ALBUM_ID"     bigint NOT NULL REFERENCES public."ALBUM_MASTER"("ALBUM_ID"),
    "MOOD"         text,                                   -- 소감 프리셋 이모지/짧은 태그
    "NOTE"         text CHECK (char_length("NOTE") <= 500),
    "LISTENED_AT"  timestamp with time zone NOT NULL DEFAULT now(),
    "CREATED_AT"   timestamp with time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "idx_listening_log_user_listened" ON public."LISTENING_LOG" ("USER_ID", "LISTENED_AT" DESC);
CREATE INDEX IF NOT EXISTS "idx_listening_log_listened_at"   ON public."LISTENING_LOG" ("LISTENED_AT" DESC); -- 전역 피드용

ALTER PUBLICATION supabase_realtime ADD TABLE public."LISTENING_LOG";

ALTER TABLE public."LISTENING_LOG" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "listening_log_read_all"   ON public."LISTENING_LOG";
DROP POLICY IF EXISTS "listening_log_insert_own" ON public."LISTENING_LOG";
DROP POLICY IF EXISTS "listening_log_update_own" ON public."LISTENING_LOG";
DROP POLICY IF EXISTS "listening_log_delete_own" ON public."LISTENING_LOG";
CREATE POLICY "listening_log_read_all"   ON public."LISTENING_LOG" FOR SELECT USING (true);
CREATE POLICY "listening_log_insert_own" ON public."LISTENING_LOG" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = "USER_ID");
CREATE POLICY "listening_log_update_own" ON public."LISTENING_LOG" FOR UPDATE TO authenticated
  USING ((select auth.uid()) = "USER_ID")
  WITH CHECK ((select auth.uid()) = "USER_ID");
CREATE POLICY "listening_log_delete_own" ON public."LISTENING_LOG" FOR DELETE TO authenticated
  USING ((select auth.uid()) = "USER_ID");

-- EVENT_LOG.EVENT_TYPE에 다이어리/랜덤픽 이벤트 추가 (NOT VALID: 기존 행에 영향 없음)
ALTER TABLE public."EVENT_LOG" DROP CONSTRAINT IF EXISTS "event_log_type_check";
ALTER TABLE public."EVENT_LOG" ADD CONSTRAINT "event_log_type_check"
  CHECK ("EVENT_TYPE" IN ('VISIT','SIGNUP','LOGIN','SEARCH','SCAN','ALBUM_ADD','WISH_ADD','SHARE','SPIN_LOG','RANDOM_PICK')) NOT VALID;

-- 2026-07-14: 스피닝 다이어리 미디어 첨부(이미지 또는 15초 내외 짧은 영상 1개).
-- 업로드는 /api/spin-log/upload 서버 라우트가 인증 검증 후 service role로
-- spin-log-media 버킷(공개 read, 25MB 제한, 이미지/영상 MIME 화이트리스트)에 저장한다.
ALTER TABLE public."LISTENING_LOG" ADD COLUMN IF NOT EXISTS "MEDIA_URL" text;
ALTER TABLE public."LISTENING_LOG" ADD COLUMN IF NOT EXISTS "MEDIA_TYPE" text CHECK ("MEDIA_TYPE" IN ('image','video'));

-- 2026-07-14: 기록별 공개/비공개 — 기본값 true(기존 동작 유지: 지금까지의
-- 모든 기록은 전체 공개였다). false로 바꾼 기록은 작성자 본인만 볼 수 있다.
ALTER TABLE public."LISTENING_LOG" ADD COLUMN IF NOT EXISTS "IS_PUBLIC" boolean NOT NULL DEFAULT true;

-- 공개 읽기 정책을 "IS_PUBLIC=true이거나 본인 글"로 좁힌다 — 비공개로 바꾼
-- 기록은 타인에게 더 이상 보이지 않지만, 작성자 본인의 /log 페이지(비공개
-- 포함 전체 조회)는 계속 정상 동작해야 하므로 auth.uid()=USER_ID는 항상 통과.
DROP POLICY IF EXISTS "listening_log_read_all" ON public."LISTENING_LOG";
CREATE POLICY "listening_log_read_all" ON public."LISTENING_LOG" FOR SELECT
  USING ("IS_PUBLIC" = true OR (select auth.uid()) = "USER_ID");

-- ============================================================
-- Today's Vinyl Story / 오늘의 바이닐 스토리 (2026-07-14)
-- Run this section manually in the Supabase SQL Editor.
--
-- 매일 명반 하나의 숨겨진 이야기를 보여주는 매거진 콘텐츠. 크론 없이
-- "조회 시 없으면 생성 후 캐싱" 방식이라 GEMINI_API_KEY를 쓰는 생성 로직은
-- 서버(service role)에서만 실행된다 — ALBUM_MASTER처럼 클라이언트 INSERT
-- 정책 자체가 없다(무단 삽입 방지, 서버 라우트가 유일한 쓰기 경로).
-- ============================================================

CREATE TABLE IF NOT EXISTS public."VINYL_STORY" (
    "STORY_ID"        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "STORY_DATE"      date NOT NULL UNIQUE,       -- KST 기준 "오늘의 앨범" 날짜
    "ALBUM_TITLE"     text NOT NULL,
    "ALBUM_ARTIST"    text NOT NULL,
    "COVER_IMAGE_URL" text,
    "HEADLINE"        text NOT NULL,
    "BODY"            text NOT NULL,
    "CREATED_AT"      timestamp with time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "idx_vinyl_story_date" ON public."VINYL_STORY" ("STORY_DATE" DESC);

ALTER TABLE public."VINYL_STORY" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "vinyl_story_read_all" ON public."VINYL_STORY";
CREATE POLICY "vinyl_story_read_all" ON public."VINYL_STORY" FOR SELECT USING (true);
-- client INSERT/UPDATE 정책 없음 — service role(서버)만 기록.

-- ============================================================
-- 유저 팔로우 + 취향 매칭 (2026-07-14)
-- Run this section manually in the Supabase SQL Editor.
--
-- 컬렉션(USER_VINYL)과 프로필(PROFILES)이 이미 전체 공개이므로 팔로우
-- 관계 공개도 새로운 노출이 아니다. 쓰기는 본인(FOLLOWER_ID = auth.uid())만.
-- ============================================================

CREATE TABLE IF NOT EXISTS public."USER_FOLLOW" (
    "FOLLOW_ID"    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FOLLOWER_ID"  uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "FOLLOWING_ID" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "CREATED_AT"   timestamp with time zone DEFAULT now(),
    CONSTRAINT "user_follow_unique"  UNIQUE ("FOLLOWER_ID", "FOLLOWING_ID"),
    CONSTRAINT "user_follow_no_self" CHECK ("FOLLOWER_ID" <> "FOLLOWING_ID")
);

CREATE INDEX IF NOT EXISTS "idx_user_follow_follower"  ON public."USER_FOLLOW" ("FOLLOWER_ID");
CREATE INDEX IF NOT EXISTS "idx_user_follow_following" ON public."USER_FOLLOW" ("FOLLOWING_ID");

ALTER TABLE public."USER_FOLLOW" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "user_follow_read_all"   ON public."USER_FOLLOW";
DROP POLICY IF EXISTS "user_follow_insert_own" ON public."USER_FOLLOW";
DROP POLICY IF EXISTS "user_follow_delete_own" ON public."USER_FOLLOW";
CREATE POLICY "user_follow_read_all"   ON public."USER_FOLLOW" FOR SELECT USING (true);
CREATE POLICY "user_follow_insert_own" ON public."USER_FOLLOW" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = "FOLLOWER_ID");
CREATE POLICY "user_follow_delete_own" ON public."USER_FOLLOW" FOR DELETE TO authenticated
  USING ((select auth.uid()) = "FOLLOWER_ID");

-- 취향 매칭: 내 OWNED 앨범과 겹치는 수가 많은 유저를 DB에서 집계한다.
-- 일치율 = 겹침 ÷ LEAST(내 수집 수, 상대 수집 수) — "상대가 내 컬렉션의
-- 부분집합이면 100%"가 되는 관대한 정의(추천 문구용). USER_VINYL이 public
-- read라 SECURITY INVOKER(기본)로도 anon/authenticated 모두 실행 가능.
CREATE OR REPLACE FUNCTION public.get_taste_matches(p_user_id uuid, p_limit int DEFAULT 10)
RETURNS TABLE (
  user_id uuid,
  display_name text,
  overlap_count bigint,
  their_count bigint,
  match_percent int
)
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  WITH mine AS (
    SELECT "ALBUM_ID" FROM public."USER_VINYL"
    WHERE "USER_ID" = p_user_id AND "STATUS" = 'OWNED'
  ),
  others AS (
    SELECT uv."USER_ID" AS uid,
           count(*) FILTER (WHERE uv."ALBUM_ID" IN (SELECT "ALBUM_ID" FROM mine)) AS overlap,
           count(*) AS total
    FROM public."USER_VINYL" uv
    WHERE uv."STATUS" = 'OWNED' AND uv."USER_ID" <> p_user_id
    GROUP BY uv."USER_ID"
  )
  SELECT o.uid,
         p."DISPLAY_NAME",
         o.overlap,
         o.total,
         round(100.0 * o.overlap / GREATEST(LEAST((SELECT count(*) FROM mine), o.total), 1))::int
  FROM others o
  LEFT JOIN public."PROFILES" p ON p."USER_ID" = o.uid
  WHERE o.overlap > 0
  ORDER BY o.overlap DESC, o.total ASC
  LIMIT p_limit;
$$;

-- EVENT_LOG.EVENT_TYPE에 FOLLOW 추가 (NOT VALID: 기존 행에 영향 없음)
ALTER TABLE public."EVENT_LOG" DROP CONSTRAINT IF EXISTS "event_log_type_check";
ALTER TABLE public."EVENT_LOG" ADD CONSTRAINT "event_log_type_check"
  CHECK ("EVENT_TYPE" IN ('VISIT','SIGNUP','LOGIN','SEARCH','SCAN','ALBUM_ADD','WISH_ADD','SHARE','SPIN_LOG','RANDOM_PICK','FOLLOW')) NOT VALID;

-- ============================================================
-- 프로필 공개/비공개 (2026-07-14, 2차)
-- Run this section manually in the Supabase SQL Editor.
--
-- IS_PUBLIC=false인 유저의 컬렉션은 본인·관리자 외에는 RLS 레벨에서
-- 조회가 차단된다 → 실시간 피드(Realtime 포함)·공유 프로필·취향 매칭에서
-- 자동으로 빠진다. PROFILES 행이 없는 유저는 공개로 간주(opt-out 방식).
-- ============================================================

ALTER TABLE public."PROFILES" ADD COLUMN IF NOT EXISTS "IS_PUBLIC" boolean NOT NULL DEFAULT true;

-- 명시적으로 비공개한 경우만 비공개 취급 (PROFILES 행 없음 = 공개)
CREATE OR REPLACE FUNCTION public.is_profile_public(p_user uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT NOT EXISTS (
    SELECT 1 FROM public."PROFILES"
    WHERE "USER_ID" = p_user AND "IS_PUBLIC" = false
  );
$$;

-- USER_VINYL 읽기: 공개 프로필 전체 공개(퍼블릭 대시보드/피드 유지),
-- 비공개 프로필은 본인 + 관리자(app_metadata.role)만.
DROP POLICY IF EXISTS "user_vinyl_read_all" ON public."USER_VINYL";
CREATE POLICY "user_vinyl_read_all" ON public."USER_VINYL" FOR SELECT
  USING (
    (select auth.uid()) = "USER_ID"
    OR public.is_profile_public("USER_ID")
    OR (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

-- 취향 매칭에서도 비공개 유저 제외
CREATE OR REPLACE FUNCTION public.get_taste_matches(p_user_id uuid, p_limit int DEFAULT 10)
RETURNS TABLE (
  user_id uuid,
  display_name text,
  overlap_count bigint,
  their_count bigint,
  match_percent int
)
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  WITH mine AS (
    SELECT "ALBUM_ID" FROM public."USER_VINYL"
    WHERE "USER_ID" = p_user_id AND "STATUS" = 'OWNED'
  ),
  others AS (
    SELECT uv."USER_ID" AS uid,
           count(*) FILTER (WHERE uv."ALBUM_ID" IN (SELECT "ALBUM_ID" FROM mine)) AS overlap,
           count(*) AS total
    FROM public."USER_VINYL" uv
    WHERE uv."STATUS" = 'OWNED'
      AND uv."USER_ID" <> p_user_id
      AND public.is_profile_public(uv."USER_ID")
    GROUP BY uv."USER_ID"
  )
  SELECT o.uid,
         p."DISPLAY_NAME",
         o.overlap,
         o.total,
         round(100.0 * o.overlap / GREATEST(LEAST((SELECT count(*) FROM mine), o.total), 1))::int
  FROM others o
  LEFT JOIN public."PROFILES" p ON p."USER_ID" = o.uid
  WHERE o.overlap > 0
  ORDER BY o.overlap DESC, o.total ASC
  LIMIT p_limit;
$$;

-- ============================================================
-- 팔로우 목록 프라이버시 (2026-07-14, 3차)
-- Run this section manually in the Supabase SQL Editor.
--
-- 팔로워/팔로잉 "목록"은 공개 프로필만 제3자에게 보인다. 비공개 유저가
-- 낀 관계 행은 당사자(팔로워/팔로잉 어느 쪽이든)와 관리자만 조회 가능 —
-- 비공개 유저는 남의 공개 팔로우 목록에서도 자동으로 빠진다.
-- ============================================================

DROP POLICY IF EXISTS "user_follow_read_all" ON public."USER_FOLLOW";
CREATE POLICY "user_follow_read_all" ON public."USER_FOLLOW" FOR SELECT
  USING (
    (select auth.uid()) IN ("FOLLOWER_ID", "FOLLOWING_ID")
    OR (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    OR (public.is_profile_public("FOLLOWER_ID") AND public.is_profile_public("FOLLOWING_ID"))
  );

-- ============================================================
-- 팔로우 요청 + 카운트/목록 RPC (2026-07-14, 4차)
-- Run this section manually in the Supabase SQL Editor.
--
-- 스펙: 비공개 프로필이어도 팔로워/팔로잉 "숫자"는 모두에게 보이고,
-- "목록"은 본인(+관리자)만. 공개 프로필은 목록도 공개. 비공개 프로필은
-- 바로 팔로우가 아니라 "팔로우 요청 → 대상자 수락" 방식.
-- (3차 섹션의 USER_FOLLOW 읽기 정책도 함께 실행돼 있어야 한다)
-- ============================================================

CREATE TABLE IF NOT EXISTS public."FOLLOW_REQUEST" (
    "REQUEST_ID"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "REQUESTER_ID" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "TARGET_ID"    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "CREATED_AT"   timestamp with time zone DEFAULT now(),
    CONSTRAINT "follow_request_unique"  UNIQUE ("REQUESTER_ID", "TARGET_ID"),
    CONSTRAINT "follow_request_no_self" CHECK ("REQUESTER_ID" <> "TARGET_ID")
);

CREATE INDEX IF NOT EXISTS "idx_follow_request_target" ON public."FOLLOW_REQUEST" ("TARGET_ID");

ALTER TABLE public."FOLLOW_REQUEST" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "follow_request_select_own" ON public."FOLLOW_REQUEST";
DROP POLICY IF EXISTS "follow_request_insert_own" ON public."FOLLOW_REQUEST";
DROP POLICY IF EXISTS "follow_request_delete_own" ON public."FOLLOW_REQUEST";
-- 조회: 당사자(요청자·대상자)와 관리자만
CREATE POLICY "follow_request_select_own" ON public."FOLLOW_REQUEST" FOR SELECT TO authenticated
  USING (
    (select auth.uid()) IN ("REQUESTER_ID", "TARGET_ID")
    OR (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );
-- 생성: 본인 명의 요청만
CREATE POLICY "follow_request_insert_own" ON public."FOLLOW_REQUEST" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = "REQUESTER_ID");
-- 삭제: 요청자(취소) 또는 대상자(거절)
CREATE POLICY "follow_request_delete_own" ON public."FOLLOW_REQUEST" FOR DELETE TO authenticated
  USING ((select auth.uid()) IN ("REQUESTER_ID", "TARGET_ID"));

-- 카운트: 비공개 프로필 포함 누구나 — 집계 숫자만 노출하므로 안전
-- (테이블 RLS는 우회하되 개별 행은 반환하지 않는다)
CREATE OR REPLACE FUNCTION public.get_follow_counts(p_user uuid)
RETURNS TABLE (followers bigint, following bigint)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    (SELECT count(*) FROM public."USER_FOLLOW" WHERE "FOLLOWING_ID" = p_user),
    (SELECT count(*) FROM public."USER_FOLLOW" WHERE "FOLLOWER_ID" = p_user);
$$;

-- 목록: 본인/관리자/공개 프로필만 — 접근 검사를 함수 안에서 수행.
-- 목록 소유자(p_user)의 공개 여부만 따지므로, 비공개 유저도 남의 공개
-- 목록 안에는 나타난다(닉네임만 노출).
CREATE OR REPLACE FUNCTION public.get_follow_list(p_user uuid, p_type text, p_limit int DEFAULT 100)
RETURNS TABLE (user_id uuid, display_name text, followed_at timestamp with time zone)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE WHEN p_type = 'followers' THEN uf."FOLLOWER_ID" ELSE uf."FOLLOWING_ID" END,
         p."DISPLAY_NAME",
         uf."CREATED_AT"
  FROM public."USER_FOLLOW" uf
  LEFT JOIN public."PROFILES" p
    ON p."USER_ID" = CASE WHEN p_type = 'followers' THEN uf."FOLLOWER_ID" ELSE uf."FOLLOWING_ID" END
  WHERE (CASE WHEN p_type = 'followers' THEN uf."FOLLOWING_ID" ELSE uf."FOLLOWER_ID" END) = p_user
    AND (
      (select auth.uid()) = p_user
      OR (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
      OR public.is_profile_public(p_user)
    )
  ORDER BY uf."CREATED_AT" DESC
  LIMIT p_limit;
$$;

-- 요청 수락: 대상자 본인만. 수락 시 요청자 명의의 USER_FOLLOW 행을 만들어야
-- 하는데 INSERT 정책(FOLLOWER_ID = auth.uid())상 대상자가 직접 넣을 수 없어
-- SECURITY DEFINER RPC로 처리한다.
CREATE OR REPLACE FUNCTION public.accept_follow_request(p_requester uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_target uuid := auth.uid();
BEGIN
  IF v_target IS NULL THEN
    RAISE EXCEPTION '로그인이 필요합니다.' USING ERRCODE = 'P0001';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public."FOLLOW_REQUEST"
    WHERE "REQUESTER_ID" = p_requester AND "TARGET_ID" = v_target
  ) THEN
    RAISE EXCEPTION '해당 팔로우 요청이 없습니다.' USING ERRCODE = 'P0001';
  END IF;
  INSERT INTO public."USER_FOLLOW" ("FOLLOWER_ID", "FOLLOWING_ID")
  VALUES (p_requester, v_target)
  ON CONFLICT ("FOLLOWER_ID", "FOLLOWING_ID") DO NOTHING;
  DELETE FROM public."FOLLOW_REQUEST"
  WHERE "REQUESTER_ID" = p_requester AND "TARGET_ID" = v_target;
END;
$$;

-- ============================================================
-- 전원 기본 비공개 전환 (2026-07-14, 5차)
-- Run this section manually in the Supabase SQL Editor.
--
-- 공개/비공개는 새로 생긴 개념이라 기존 유저가 "원치 않은 공개" 상태가
-- 되지 않도록 전원 비공개로 초기화하고, 이후 가입자도 기본 비공개(opt-in
-- 공개)로 한다. is_profile_public()도 "명시적으로 공개한 경우만 공개"로
-- 재정의 — PROFILES 행이 없는 계정(닉네임 미설정)도 자동으로 비공개다.
-- ============================================================

ALTER TABLE public."PROFILES" ALTER COLUMN "IS_PUBLIC" SET DEFAULT false;
UPDATE public."PROFILES" SET "IS_PUBLIC" = false;

CREATE OR REPLACE FUNCTION public.is_profile_public(p_user uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public."PROFILES"
    WHERE "USER_ID" = p_user AND "IS_PUBLIC" = true
  );
$$;

-- ============================================================
-- 팔로워 열람 허용 (2026-07-14, 6차)
-- Run this section manually in the Supabase SQL Editor.
--
-- 비공개 프로필이어도 "수락된 팔로워"는 해당 유저의 콘텐츠(보관함,
-- 피드 노출, 팔로우 목록)를 볼 수 있다 — 인스타그램 비공개 계정 방식.
-- 열람 판정을 can_view_profile() 하나로 모은다:
--   본인 OR 공개 프로필 OR 관리자 OR 수락된 팔로워
-- ============================================================

CREATE OR REPLACE FUNCTION public.can_view_profile(p_owner uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT (select auth.uid()) = p_owner
      OR public.is_profile_public(p_owner)
      OR (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
      OR EXISTS (
           SELECT 1 FROM public."USER_FOLLOW"
           WHERE "FOLLOWING_ID" = p_owner
             AND "FOLLOWER_ID" = (select auth.uid())
         );
$$;

-- USER_VINYL 읽기: 열람 판정을 can_view_profile()로 일원화
DROP POLICY IF EXISTS "user_vinyl_read_all" ON public."USER_VINYL";
CREATE POLICY "user_vinyl_read_all" ON public."USER_VINYL" FOR SELECT
  USING (public.can_view_profile("USER_ID"));

-- 팔로우 목록도 수락된 팔로워에게 공개
CREATE OR REPLACE FUNCTION public.get_follow_list(p_user uuid, p_type text, p_limit int DEFAULT 100)
RETURNS TABLE (user_id uuid, display_name text, followed_at timestamp with time zone)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE WHEN p_type = 'followers' THEN uf."FOLLOWER_ID" ELSE uf."FOLLOWING_ID" END,
         p."DISPLAY_NAME",
         uf."CREATED_AT"
  FROM public."USER_FOLLOW" uf
  LEFT JOIN public."PROFILES" p
    ON p."USER_ID" = CASE WHEN p_type = 'followers' THEN uf."FOLLOWER_ID" ELSE uf."FOLLOWING_ID" END
  WHERE (CASE WHEN p_type = 'followers' THEN uf."FOLLOWING_ID" ELSE uf."FOLLOWER_ID" END) = p_user
    AND public.can_view_profile(p_user)
  ORDER BY uf."CREATED_AT" DESC
  LIMIT p_limit;
$$;

-- ============================================================
-- 스피닝 다이어리 프로필 프라이버시 연동 (2026-07-14, 7차)
-- Run this section manually in the Supabase SQL Editor.
--
-- 공개(IS_PUBLIC=true) 재생 기록도 프로필 열람 권한이 있는 사람
-- (본인/공개 프로필/관리자/수락된 팔로워)에게만 보이도록 일원화.
-- 비공개 기록은 종전대로 본인만.
-- ============================================================

DROP POLICY IF EXISTS "listening_log_read_all" ON public."LISTENING_LOG";
CREATE POLICY "listening_log_read_all" ON public."LISTENING_LOG" FOR SELECT
  USING (
    ("IS_PUBLIC" = true AND public.can_view_profile("USER_ID"))
    OR (select auth.uid()) = "USER_ID"
  );

-- ============================================================
-- 스피닝 다이어리 소셜 — 좋아요/댓글(답글)/저장/신고 (2026-07-14, 8차)
-- Run this section manually in the Supabase SQL Editor.
--
-- 모든 상호작용은 "그 기록을 볼 수 있는 사람"(LISTENING_LOG RLS 통과)만
-- 가능하다 — 정책의 EXISTS 서브쿼리가 LISTENING_LOG의 RLS를 그대로 타므로
-- 비공개 프로필/비공개 기록에는 좋아요·댓글 자체가 불가능하다.
-- ============================================================

-- 좋아요
CREATE TABLE IF NOT EXISTS public."SPIN_LOG_LIKE" (
    "LIKE_ID"    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LOG_ID"     bigint NOT NULL REFERENCES public."LISTENING_LOG"("LOG_ID") ON DELETE CASCADE,
    "USER_ID"    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "CREATED_AT" timestamp with time zone DEFAULT now(),
    CONSTRAINT "spin_like_unique" UNIQUE ("LOG_ID", "USER_ID")
);
CREATE INDEX IF NOT EXISTS "idx_spin_like_log" ON public."SPIN_LOG_LIKE" ("LOG_ID");

ALTER TABLE public."SPIN_LOG_LIKE" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "spin_like_select" ON public."SPIN_LOG_LIKE";
DROP POLICY IF EXISTS "spin_like_insert" ON public."SPIN_LOG_LIKE";
DROP POLICY IF EXISTS "spin_like_delete" ON public."SPIN_LOG_LIKE";
CREATE POLICY "spin_like_select" ON public."SPIN_LOG_LIKE" FOR SELECT
  USING (EXISTS (SELECT 1 FROM public."LISTENING_LOG" l WHERE l."LOG_ID" = "SPIN_LOG_LIKE"."LOG_ID"));
CREATE POLICY "spin_like_insert" ON public."SPIN_LOG_LIKE" FOR INSERT TO authenticated
  WITH CHECK (
    (select auth.uid()) = "USER_ID"
    AND EXISTS (SELECT 1 FROM public."LISTENING_LOG" l WHERE l."LOG_ID" = "SPIN_LOG_LIKE"."LOG_ID")
  );
CREATE POLICY "spin_like_delete" ON public."SPIN_LOG_LIKE" FOR DELETE TO authenticated
  USING ((select auth.uid()) = "USER_ID");

-- 댓글 (PARENT_COMMENT_ID로 1단계 답글 스레딩)
CREATE TABLE IF NOT EXISTS public."SPIN_LOG_COMMENT" (
    "COMMENT_ID"        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LOG_ID"            bigint NOT NULL REFERENCES public."LISTENING_LOG"("LOG_ID") ON DELETE CASCADE,
    "USER_ID"           uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "PARENT_COMMENT_ID" bigint REFERENCES public."SPIN_LOG_COMMENT"("COMMENT_ID") ON DELETE CASCADE,
    "CONTENT"           text NOT NULL CHECK (char_length("CONTENT") BETWEEN 1 AND 500),
    "CREATED_AT"        timestamp with time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_spin_comment_log" ON public."SPIN_LOG_COMMENT" ("LOG_ID", "CREATED_AT");

ALTER TABLE public."SPIN_LOG_COMMENT" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "spin_comment_select" ON public."SPIN_LOG_COMMENT";
DROP POLICY IF EXISTS "spin_comment_insert" ON public."SPIN_LOG_COMMENT";
DROP POLICY IF EXISTS "spin_comment_delete" ON public."SPIN_LOG_COMMENT";
CREATE POLICY "spin_comment_select" ON public."SPIN_LOG_COMMENT" FOR SELECT
  USING (EXISTS (SELECT 1 FROM public."LISTENING_LOG" l WHERE l."LOG_ID" = "SPIN_LOG_COMMENT"."LOG_ID"));
CREATE POLICY "spin_comment_insert" ON public."SPIN_LOG_COMMENT" FOR INSERT TO authenticated
  WITH CHECK (
    (select auth.uid()) = "USER_ID"
    AND EXISTS (SELECT 1 FROM public."LISTENING_LOG" l WHERE l."LOG_ID" = "SPIN_LOG_COMMENT"."LOG_ID")
  );
-- 삭제: 댓글 작성자 본인 또는 그 다이어리 기록의 주인(자기 게시물 관리)
CREATE POLICY "spin_comment_delete" ON public."SPIN_LOG_COMMENT" FOR DELETE TO authenticated
  USING (
    (select auth.uid()) = "USER_ID"
    OR (select auth.uid()) = (SELECT l."USER_ID" FROM public."LISTENING_LOG" l WHERE l."LOG_ID" = "SPIN_LOG_COMMENT"."LOG_ID")
  );

-- 저장(북마크) — 저장 목록은 본인만 조회
CREATE TABLE IF NOT EXISTS public."SPIN_LOG_SAVE" (
    "SAVE_ID"    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LOG_ID"     bigint NOT NULL REFERENCES public."LISTENING_LOG"("LOG_ID") ON DELETE CASCADE,
    "USER_ID"    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "CREATED_AT" timestamp with time zone DEFAULT now(),
    CONSTRAINT "spin_save_unique" UNIQUE ("LOG_ID", "USER_ID")
);
CREATE INDEX IF NOT EXISTS "idx_spin_save_user" ON public."SPIN_LOG_SAVE" ("USER_ID");

ALTER TABLE public."SPIN_LOG_SAVE" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "spin_save_select" ON public."SPIN_LOG_SAVE";
DROP POLICY IF EXISTS "spin_save_insert" ON public."SPIN_LOG_SAVE";
DROP POLICY IF EXISTS "spin_save_delete" ON public."SPIN_LOG_SAVE";
CREATE POLICY "spin_save_select" ON public."SPIN_LOG_SAVE" FOR SELECT TO authenticated
  USING ((select auth.uid()) = "USER_ID");
CREATE POLICY "spin_save_insert" ON public."SPIN_LOG_SAVE" FOR INSERT TO authenticated
  WITH CHECK (
    (select auth.uid()) = "USER_ID"
    AND EXISTS (SELECT 1 FROM public."LISTENING_LOG" l WHERE l."LOG_ID" = "SPIN_LOG_SAVE"."LOG_ID")
  );
CREATE POLICY "spin_save_delete" ON public."SPIN_LOG_SAVE" FOR DELETE TO authenticated
  USING ((select auth.uid()) = "USER_ID");

-- 신고 — 접수는 로그인 유저 누구나(기록당 1회), 열람은 본인 신고분/관리자만
CREATE TABLE IF NOT EXISTS public."SPIN_LOG_REPORT" (
    "REPORT_ID"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LOG_ID"      bigint NOT NULL REFERENCES public."LISTENING_LOG"("LOG_ID") ON DELETE CASCADE,
    "REPORTER_ID" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "REASON"      text CHECK (char_length("REASON") <= 300),
    "CREATED_AT"  timestamp with time zone DEFAULT now(),
    CONSTRAINT "spin_report_unique" UNIQUE ("LOG_ID", "REPORTER_ID")
);

ALTER TABLE public."SPIN_LOG_REPORT" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "spin_report_select" ON public."SPIN_LOG_REPORT";
DROP POLICY IF EXISTS "spin_report_insert" ON public."SPIN_LOG_REPORT";
CREATE POLICY "spin_report_select" ON public."SPIN_LOG_REPORT" FOR SELECT TO authenticated
  USING (
    (select auth.uid()) = "REPORTER_ID"
    OR (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );
CREATE POLICY "spin_report_insert" ON public."SPIN_LOG_REPORT" FOR INSERT TO authenticated
  WITH CHECK (
    (select auth.uid()) = "REPORTER_ID"
    AND EXISTS (SELECT 1 FROM public."LISTENING_LOG" l WHERE l."LOG_ID" = "SPIN_LOG_REPORT"."LOG_ID")
  );

-- ============================================================
-- 알림함 (2026-07-14, 9차)
-- Run this section manually in the Supabase SQL Editor.
--
-- 좋아요/댓글/답글/팔로우 이벤트를 DB 트리거가 NOTIFICATION으로 적재한다
-- (클라이언트 협조 불필요 — 웹/모바일 어디서 발생해도 쌓임). 좋아요 취소나
-- 팔로우 요청 취소 시 해당 알림도 정리. 클라이언트 INSERT 정책 없음.
-- ============================================================

CREATE TABLE IF NOT EXISTS public."NOTIFICATION" (
    "NOTIFICATION_ID"  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "USER_ID"          uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,   -- 수신자
    "ACTOR_ID"         uuid REFERENCES auth.users(id) ON DELETE CASCADE,            -- 행위자
    "TYPE"             text NOT NULL CHECK ("TYPE" IN (
        'SPIN_LIKE','SPIN_COMMENT','SPIN_REPLY',
        'VINYL_LIKE','VINYL_COMMENT','VINYL_REPLY',
        'FOLLOW_REQUEST','FOLLOW_ACCEPTED','NEW_FOLLOWER')),
    "LOG_ID"           bigint REFERENCES public."LISTENING_LOG"("LOG_ID") ON DELETE CASCADE,
    "USER_VINYL_ID"    bigint REFERENCES public."USER_VINYL"("USER_VINYL_ID") ON DELETE CASCADE,
    "SPIN_COMMENT_ID"  bigint REFERENCES public."SPIN_LOG_COMMENT"("COMMENT_ID") ON DELETE CASCADE,
    "VINYL_COMMENT_ID" bigint REFERENCES public."VINYL_COMMENT"("COMMENT_ID") ON DELETE CASCADE,
    "COMMENT_PREVIEW"  text,                                                        -- 댓글 앞 80자
    "READ_AT"          timestamp with time zone,
    "CREATED_AT"       timestamp with time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_notification_user" ON public."NOTIFICATION" ("USER_ID", "CREATED_AT" DESC);

ALTER TABLE public."NOTIFICATION" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "notification_select_own" ON public."NOTIFICATION";
DROP POLICY IF EXISTS "notification_update_own" ON public."NOTIFICATION";
DROP POLICY IF EXISTS "notification_delete_own" ON public."NOTIFICATION";
CREATE POLICY "notification_select_own" ON public."NOTIFICATION" FOR SELECT TO authenticated
  USING ((select auth.uid()) = "USER_ID");
CREATE POLICY "notification_update_own" ON public."NOTIFICATION" FOR UPDATE TO authenticated
  USING ((select auth.uid()) = "USER_ID")
  WITH CHECK ((select auth.uid()) = "USER_ID");
CREATE POLICY "notification_delete_own" ON public."NOTIFICATION" FOR DELETE TO authenticated
  USING ((select auth.uid()) = "USER_ID");

-- 미읽음 배지 실시간 갱신용 (RLS가 수신자 본인에게만 이벤트 전달)
-- 이미 등록돼 있으면 무시 — 섹션 전체 재실행에 안전하도록
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public."NOTIFICATION";
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── 트리거들 (SECURITY DEFINER — NOTIFICATION에 클라이언트 INSERT 정책이 없으므로) ──

-- 다이어리 좋아요
CREATE OR REPLACE FUNCTION public.notify_spin_like() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_owner uuid;
BEGIN
  SELECT "USER_ID" INTO v_owner FROM public."LISTENING_LOG" WHERE "LOG_ID" = NEW."LOG_ID";
  IF v_owner IS NOT NULL AND v_owner <> NEW."USER_ID" THEN
    INSERT INTO public."NOTIFICATION" ("USER_ID","ACTOR_ID","TYPE","LOG_ID")
    VALUES (v_owner, NEW."USER_ID", 'SPIN_LIKE', NEW."LOG_ID");
  END IF;
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_notify_spin_like ON public."SPIN_LOG_LIKE";
CREATE TRIGGER trg_notify_spin_like AFTER INSERT ON public."SPIN_LOG_LIKE"
  FOR EACH ROW EXECUTE FUNCTION public.notify_spin_like();

-- 좋아요 취소 시 알림 정리
CREATE OR REPLACE FUNCTION public.unnotify_spin_like() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  DELETE FROM public."NOTIFICATION"
  WHERE "TYPE" = 'SPIN_LIKE' AND "LOG_ID" = OLD."LOG_ID" AND "ACTOR_ID" = OLD."USER_ID";
  RETURN OLD;
END; $$;
DROP TRIGGER IF EXISTS trg_unnotify_spin_like ON public."SPIN_LOG_LIKE";
CREATE TRIGGER trg_unnotify_spin_like AFTER DELETE ON public."SPIN_LOG_LIKE"
  FOR EACH ROW EXECUTE FUNCTION public.unnotify_spin_like();

-- 다이어리 댓글/답글
CREATE OR REPLACE FUNCTION public.notify_spin_comment() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_owner uuid; v_parent_author uuid;
BEGIN
  SELECT "USER_ID" INTO v_owner FROM public."LISTENING_LOG" WHERE "LOG_ID" = NEW."LOG_ID";
  IF NEW."PARENT_COMMENT_ID" IS NOT NULL THEN
    SELECT "USER_ID" INTO v_parent_author FROM public."SPIN_LOG_COMMENT" WHERE "COMMENT_ID" = NEW."PARENT_COMMENT_ID";
  END IF;
  -- 답글: 부모 댓글 작성자에게
  IF v_parent_author IS NOT NULL AND v_parent_author <> NEW."USER_ID" THEN
    INSERT INTO public."NOTIFICATION" ("USER_ID","ACTOR_ID","TYPE","LOG_ID","SPIN_COMMENT_ID","COMMENT_PREVIEW")
    VALUES (v_parent_author, NEW."USER_ID", 'SPIN_REPLY', NEW."LOG_ID", NEW."COMMENT_ID", left(NEW."CONTENT", 80));
  END IF;
  -- 댓글: 기록 주인에게 (답글 수신자와 중복이면 생략)
  IF v_owner IS NOT NULL AND v_owner <> NEW."USER_ID"
     AND (v_parent_author IS NULL OR v_owner <> v_parent_author) THEN
    INSERT INTO public."NOTIFICATION" ("USER_ID","ACTOR_ID","TYPE","LOG_ID","SPIN_COMMENT_ID","COMMENT_PREVIEW")
    VALUES (v_owner, NEW."USER_ID", 'SPIN_COMMENT', NEW."LOG_ID", NEW."COMMENT_ID", left(NEW."CONTENT", 80));
  END IF;
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_notify_spin_comment ON public."SPIN_LOG_COMMENT";
CREATE TRIGGER trg_notify_spin_comment AFTER INSERT ON public."SPIN_LOG_COMMENT"
  FOR EACH ROW EXECUTE FUNCTION public.notify_spin_comment();

-- 수집 게시물(피드) 좋아요
CREATE OR REPLACE FUNCTION public.notify_vinyl_like() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_owner uuid;
BEGIN
  SELECT "USER_ID" INTO v_owner FROM public."USER_VINYL" WHERE "USER_VINYL_ID" = NEW."USER_VINYL_ID";
  IF v_owner IS NOT NULL AND v_owner <> NEW."USER_ID" THEN
    INSERT INTO public."NOTIFICATION" ("USER_ID","ACTOR_ID","TYPE","USER_VINYL_ID")
    VALUES (v_owner, NEW."USER_ID", 'VINYL_LIKE', NEW."USER_VINYL_ID");
  END IF;
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_notify_vinyl_like ON public."VINYL_LIKE";
CREATE TRIGGER trg_notify_vinyl_like AFTER INSERT ON public."VINYL_LIKE"
  FOR EACH ROW EXECUTE FUNCTION public.notify_vinyl_like();

CREATE OR REPLACE FUNCTION public.unnotify_vinyl_like() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  DELETE FROM public."NOTIFICATION"
  WHERE "TYPE" = 'VINYL_LIKE' AND "USER_VINYL_ID" = OLD."USER_VINYL_ID" AND "ACTOR_ID" = OLD."USER_ID";
  RETURN OLD;
END; $$;
DROP TRIGGER IF EXISTS trg_unnotify_vinyl_like ON public."VINYL_LIKE";
CREATE TRIGGER trg_unnotify_vinyl_like AFTER DELETE ON public."VINYL_LIKE"
  FOR EACH ROW EXECUTE FUNCTION public.unnotify_vinyl_like();

-- 수집 게시물 댓글/답글
CREATE OR REPLACE FUNCTION public.notify_vinyl_comment() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_owner uuid; v_parent_author uuid;
BEGIN
  SELECT "USER_ID" INTO v_owner FROM public."USER_VINYL" WHERE "USER_VINYL_ID" = NEW."USER_VINYL_ID";
  IF NEW."PARENT_COMMENT_ID" IS NOT NULL THEN
    SELECT "USER_ID" INTO v_parent_author FROM public."VINYL_COMMENT" WHERE "COMMENT_ID" = NEW."PARENT_COMMENT_ID";
  END IF;
  IF v_parent_author IS NOT NULL AND v_parent_author <> NEW."USER_ID" THEN
    INSERT INTO public."NOTIFICATION" ("USER_ID","ACTOR_ID","TYPE","USER_VINYL_ID","VINYL_COMMENT_ID","COMMENT_PREVIEW")
    VALUES (v_parent_author, NEW."USER_ID", 'VINYL_REPLY', NEW."USER_VINYL_ID", NEW."COMMENT_ID", left(NEW."CONTENT", 80));
  END IF;
  IF v_owner IS NOT NULL AND v_owner <> NEW."USER_ID"
     AND (v_parent_author IS NULL OR v_owner <> v_parent_author) THEN
    INSERT INTO public."NOTIFICATION" ("USER_ID","ACTOR_ID","TYPE","USER_VINYL_ID","VINYL_COMMENT_ID","COMMENT_PREVIEW")
    VALUES (v_owner, NEW."USER_ID", 'VINYL_COMMENT', NEW."USER_VINYL_ID", NEW."COMMENT_ID", left(NEW."CONTENT", 80));
  END IF;
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_notify_vinyl_comment ON public."VINYL_COMMENT";
CREATE TRIGGER trg_notify_vinyl_comment AFTER INSERT ON public."VINYL_COMMENT"
  FOR EACH ROW EXECUTE FUNCTION public.notify_vinyl_comment();

-- 팔로우 요청 (취소 시 알림 정리 포함)
CREATE OR REPLACE FUNCTION public.notify_follow_request() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public."NOTIFICATION" ("USER_ID","ACTOR_ID","TYPE")
  VALUES (NEW."TARGET_ID", NEW."REQUESTER_ID", 'FOLLOW_REQUEST');
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_notify_follow_request ON public."FOLLOW_REQUEST";
CREATE TRIGGER trg_notify_follow_request AFTER INSERT ON public."FOLLOW_REQUEST"
  FOR EACH ROW EXECUTE FUNCTION public.notify_follow_request();

CREATE OR REPLACE FUNCTION public.unnotify_follow_request() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  DELETE FROM public."NOTIFICATION"
  WHERE "TYPE" = 'FOLLOW_REQUEST' AND "USER_ID" = OLD."TARGET_ID" AND "ACTOR_ID" = OLD."REQUESTER_ID";
  RETURN OLD;
END; $$;
DROP TRIGGER IF EXISTS trg_unnotify_follow_request ON public."FOLLOW_REQUEST";
CREATE TRIGGER trg_unnotify_follow_request AFTER DELETE ON public."FOLLOW_REQUEST"
  FOR EACH ROW EXECUTE FUNCTION public.unnotify_follow_request();

-- 팔로우 성립: 대상자가 수락한 경우(요청 플로우)면 요청자에게 "수락됨",
-- 요청자가 직접 팔로우한 경우(공개 프로필)면 대상자에게 "새 팔로워"
CREATE OR REPLACE FUNCTION public.notify_new_follow() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF (select auth.uid()) = NEW."FOLLOWING_ID" THEN
    INSERT INTO public."NOTIFICATION" ("USER_ID","ACTOR_ID","TYPE")
    VALUES (NEW."FOLLOWER_ID", NEW."FOLLOWING_ID", 'FOLLOW_ACCEPTED');
  ELSE
    INSERT INTO public."NOTIFICATION" ("USER_ID","ACTOR_ID","TYPE")
    VALUES (NEW."FOLLOWING_ID", NEW."FOLLOWER_ID", 'NEW_FOLLOWER');
  END IF;
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_notify_new_follow ON public."USER_FOLLOW";
CREATE TRIGGER trg_notify_new_follow AFTER INSERT ON public."USER_FOLLOW"
  FOR EACH ROW EXECUTE FUNCTION public.notify_new_follow();

-- ============================================================
-- SIGNUP_NUMBER upsert-burn fix (2026-07-14)
-- Run this whole section manually in the Supabase SQL Editor.
--
-- The 2026-07-12 migration drew nextval() in a BEFORE INSERT trigger.
-- But app writes to PROFILES are upserts (nickname save/change) — on an
-- existing row the INSERT branch still consumes nextval() before the
-- conflict falls through to the UPDATE path, so every nickname upsert
-- burned a number and new signups skipped ahead (live data 2026-07-14:
-- the 32nd–35th profiles got #36, #42, #43, #44).
-- ============================================================

-- 1. BEFORE trigger no longer touches the sequence. INSERT strips
--    whatever the client sent (tamper guard); UPDATE keeps the number
--    immutable once assigned. A NULL OLD value still passes through so
--    step 2's AFTER-INSERT grant (and step 3's renumber) can land.
CREATE OR REPLACE FUNCTION public.assign_signup_number()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW."SIGNUP_NUMBER" := NULL;
  ELSIF OLD."SIGNUP_NUMBER" IS NOT NULL THEN
    -- Already assigned — immutable, ignore whatever the client sent.
    NEW."SIGNUP_NUMBER" := OLD."SIGNUP_NUMBER";
  END IF;
  RETURN NEW;
END;
$$;

-- 2. Numbers are granted AFTER INSERT instead — this trigger only fires
--    when a row is actually inserted, never on an upsert's conflict/
--    UPDATE path, so the sequence can no longer burn.
CREATE OR REPLACE FUNCTION public.grant_signup_number()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public."PROFILES"
     SET "SIGNUP_NUMBER" = nextval('public.profiles_signup_seq')
   WHERE "USER_ID" = NEW."USER_ID" AND "SIGNUP_NUMBER" IS NULL;
  RETURN NULL;
END;
$$;
DROP TRIGGER IF EXISTS trg_grant_signup_number ON public."PROFILES";
CREATE TRIGGER trg_grant_signup_number
  AFTER INSERT ON public."PROFILES"
  FOR EACH ROW EXECUTE FUNCTION public.grant_signup_number();

-- 3. Renumber every profile by real signup order (same statement as the
--    2026-07-12 migration's step 4 — safe to re-run). Fixes the four
--    inflated rows; everyone else keeps their current number.
ALTER TABLE public."PROFILES" DISABLE TRIGGER trg_assign_signup_number;
WITH ordered AS (
  SELECT p."USER_ID", row_number() OVER (ORDER BY u.created_at) AS rn
  FROM public."PROFILES" p
  JOIN auth.users u ON u.id = p."USER_ID"
)
UPDATE public."PROFILES" p
SET "SIGNUP_NUMBER" = ordered.rn
FROM ordered
WHERE p."USER_ID" = ordered."USER_ID";
ALTER TABLE public."PROFILES" ENABLE TRIGGER trg_assign_signup_number;

-- 4. Pull the sequence back so the next real signup continues the count.
SELECT setval('public.profiles_signup_seq', GREATEST((SELECT count(*) FROM public."PROFILES"), 1));
