-- 커뮤니티 게시판 확장: 자랑 하위 카테고리(컬렉션/위시리스트), 게시글·댓글
-- 수정, 게시글 좋아요("울림") (2026-08-04)
-- Run this whole file manually in the Supabase SQL Editor.
--
-- 이 파일의 변경은 전부 "widen"(허용 범위 추가)이거나 "새 정책/새 테이블"이라
-- 기존에 배포된 코드의 동작을 바꾸지 않는다 — DB-001 사고 때처럼 이미 살아있는
-- INSERT 경로를 좁히는 변경이 아니므로, 의존 코드 배포를 기다리지 않고 먼저
-- 실행해도 안전하다.

-- ── 1) 자랑 하위 카테고리 추가: COLLECTION(컬렉션), WISHLIST(위시리스트) ──
-- 기존 ARRIVAL(오늘 온 전리품)/LISTENING_ROOM(나만의 청음실)과 같은 "자랑" 탭
-- 아래 추가되는 두 카테고리 — 컬렉션은 보유 앨범 중 아무거나, 위시리스트는
-- 위시 항목만 다중 선택해 자랑하는 전용 글쓰기 카테고리다.
ALTER TABLE public."COMMUNITY_POST" DROP CONSTRAINT IF EXISTS "community_post_category_check";
ALTER TABLE public."COMMUNITY_POST" ADD CONSTRAINT "community_post_category_check"
  CHECK ("CATEGORY" IN ('ARRIVAL', 'FREE', 'QNA', 'INFO', 'LISTENING_ROOM', 'TIP', 'COLLECTION', 'WISHLIST'));

-- 앨범 다중 첨부(COMMUNITY_POST_ALBUM)는 지금까지 ARRIVAL 전용이었다 —
-- COLLECTION/WISHLIST 글에서도 같은 방식으로 앨범을 첨부할 수 있게 넓힌다.
DROP POLICY IF EXISTS "community_post_album_insert_own" ON public."COMMUNITY_POST_ALBUM";
CREATE POLICY "community_post_album_insert_own" ON public."COMMUNITY_POST_ALBUM" FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public."COMMUNITY_POST" p
      WHERE p."POST_ID" = "COMMUNITY_POST_ALBUM"."POST_ID"
        AND p."AUTHOR_ID" = (select auth.uid())
        AND p."CATEGORY" IN ('ARRIVAL', 'COLLECTION', 'WISHLIST')
    )
  );

-- ── 2) 댓글 수정 허용 ──────────────────────────────────────────────
-- COMMUNITY_COMMENT는 지금까지 UPDATE 정책 자체가 없어(읽기/작성/삭제만
-- 있었음) 작성자 본인도 댓글을 고칠 수 없었다. QnA 채택 답변 판정은 여전히
-- COMMUNITY_POST.ACCEPTED_COMMENT_ID 쪽 정책이라 이 정책과 무관하다.
DROP POLICY IF EXISTS "community_comment_update_own" ON public."COMMUNITY_COMMENT";
CREATE POLICY "community_comment_update_own" ON public."COMMUNITY_COMMENT" FOR UPDATE TO authenticated
  USING ((select auth.uid()) = "USER_ID")
  WITH CHECK ((select auth.uid()) = "USER_ID");

-- ── 3) 게시글 좋아요("울림") — COMMUNITY_COMMENT_LIKE와 동일한 패턴 ──────
CREATE TABLE IF NOT EXISTS public."COMMUNITY_POST_LIKE" (
    "LIKE_ID"    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "POST_ID"    bigint NOT NULL REFERENCES public."COMMUNITY_POST"("POST_ID") ON DELETE CASCADE,
    "USER_ID"    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "CREATED_AT" timestamp with time zone DEFAULT now(),
    CONSTRAINT "community_post_like_unique" UNIQUE ("POST_ID", "USER_ID")
);
CREATE INDEX IF NOT EXISTS "idx_community_post_like_post" ON public."COMMUNITY_POST_LIKE" ("POST_ID");

ALTER TABLE public."COMMUNITY_POST_LIKE" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "community_post_like_read_all"   ON public."COMMUNITY_POST_LIKE";
DROP POLICY IF EXISTS "community_post_like_insert_own" ON public."COMMUNITY_POST_LIKE";
DROP POLICY IF EXISTS "community_post_like_delete_own"  ON public."COMMUNITY_POST_LIKE";
CREATE POLICY "community_post_like_read_all" ON public."COMMUNITY_POST_LIKE" FOR SELECT USING (true);
CREATE POLICY "community_post_like_insert_own" ON public."COMMUNITY_POST_LIKE" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = "USER_ID");
CREATE POLICY "community_post_like_delete_own" ON public."COMMUNITY_POST_LIKE" FOR DELETE TO authenticated
  USING ((select auth.uid()) = "USER_ID");
