-- Create ALBUM_MASTER Table
CREATE TABLE public."ALBUM_MASTER" (
    "ALBUM_ID" bigint PRIMARY KEY,
    "TITLE" text NOT NULL,
    "ARTIST" text NOT NULL,
    "RELEASE_YEAR" integer,
    "IMAGE_URL" text,
    "VINYL_IMAGE_URL" text,
    "CUSTOM_COLOR_HEX" text,
    "CUSTOM_STYLE_TYPE" text,
    "TRACKS" jsonb
);

-- Create USER_VINYL Table
CREATE TABLE public."USER_VINYL" (
    "USER_VINYL_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "USER_ID" bigint NOT NULL,
    "ALBUM_ID" bigint NOT NULL REFERENCES public."ALBUM_MASTER"("ALBUM_ID"),
    "STATUS" text NOT NULL,
    "PURCHASE_DATE" timestamp with time zone,
    "PURCHASE_PRICE" integer,
    "ADDED_AT" timestamp with time zone DEFAULT now()
);

-- Create VINYL_TAG Table
CREATE TABLE public."VINYL_TAG" (
    "TAG_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ALBUM_ID" bigint NOT NULL REFERENCES public."ALBUM_MASTER"("ALBUM_ID"),
    "TAG_TYPE" text,
    "TAG_NAME" text NOT NULL
);

-- Enable Supabase Realtime for the USER_VINYL table
-- This allows our apps to receive instant updates when a vinyl is added or modified
ALTER PUBLICATION supabase_realtime ADD TABLE public."USER_VINYL";

-- Add MARKET_PRICE column to ALBUM_MASTER Table
-- Run this manually in the Supabase SQL Editor: the column was missing, which
-- caused createAlbumMaster() to strip MARKET_PRICE from every save (PGRST204).
ALTER TABLE public."ALBUM_MASTER" ADD COLUMN IF NOT EXISTS "MARKET_PRICE" integer;

-- ============================================================
-- Row Level Security (RLS)
-- Run this manually in the Supabase SQL Editor.
--
-- Access model:
--   * Anyone (including logged-out visitors) can READ everything —
--     public dashboards (/user/[id]) must render collections for
--     non-members.
--   * Only authenticated users can WRITE, and USER_VINYL/PROFILES
--     rows can only be written by their owner (auth.uid()).
--   * ALBUM_MASTER/VINYL_TAG are shared master data: any signed-in
--     user may insert/update (scan & search flows create these),
--     but anonymous clients may not.
-- ============================================================

-- ALBUM_MASTER: public read / authenticated write / no delete
ALTER TABLE public."ALBUM_MASTER" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "album_master_read_all"    ON public."ALBUM_MASTER";
DROP POLICY IF EXISTS "album_master_insert_auth" ON public."ALBUM_MASTER";
DROP POLICY IF EXISTS "album_master_update_auth" ON public."ALBUM_MASTER";
CREATE POLICY "album_master_read_all"    ON public."ALBUM_MASTER" FOR SELECT USING (true);
CREATE POLICY "album_master_insert_auth" ON public."ALBUM_MASTER" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "album_master_update_auth" ON public."ALBUM_MASTER" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- VINYL_TAG: public read / authenticated write (rewritten alongside ALBUM_MASTER)
ALTER TABLE public."VINYL_TAG" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "vinyl_tag_read_all"    ON public."VINYL_TAG";
DROP POLICY IF EXISTS "vinyl_tag_insert_auth" ON public."VINYL_TAG";
DROP POLICY IF EXISTS "vinyl_tag_delete_auth" ON public."VINYL_TAG";
CREATE POLICY "vinyl_tag_read_all"    ON public."VINYL_TAG" FOR SELECT USING (true);
CREATE POLICY "vinyl_tag_insert_auth" ON public."VINYL_TAG" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "vinyl_tag_delete_auth" ON public."VINYL_TAG" FOR DELETE TO authenticated USING (true);

-- USER_VINYL: public read / owner-only write
ALTER TABLE public."USER_VINYL" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "user_vinyl_read_all"     ON public."USER_VINYL";
DROP POLICY IF EXISTS "user_vinyl_insert_own"   ON public."USER_VINYL";
DROP POLICY IF EXISTS "user_vinyl_update_own"   ON public."USER_VINYL";
DROP POLICY IF EXISTS "user_vinyl_delete_own"   ON public."USER_VINYL";
CREATE POLICY "user_vinyl_read_all"   ON public."USER_VINYL" FOR SELECT USING (true);
CREATE POLICY "user_vinyl_insert_own" ON public."USER_VINYL" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid())::text = "USER_ID"::text);
CREATE POLICY "user_vinyl_update_own" ON public."USER_VINYL" FOR UPDATE TO authenticated
  USING ((select auth.uid())::text = "USER_ID"::text)
  WITH CHECK ((select auth.uid())::text = "USER_ID"::text);
CREATE POLICY "user_vinyl_delete_own" ON public."USER_VINYL" FOR DELETE TO authenticated
  USING ((select auth.uid())::text = "USER_ID"::text);

-- PROFILES: public read (nickname display) / owner-only write
ALTER TABLE public."PROFILES" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "profiles_read_all"   ON public."PROFILES";
DROP POLICY IF EXISTS "profiles_insert_own" ON public."PROFILES";
DROP POLICY IF EXISTS "profiles_update_own" ON public."PROFILES";
CREATE POLICY "profiles_read_all"   ON public."PROFILES" FOR SELECT USING (true);
CREATE POLICY "profiles_insert_own" ON public."PROFILES" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid())::text = "USER_ID"::text);
CREATE POLICY "profiles_update_own" ON public."PROFILES" FOR UPDATE TO authenticated
  USING ((select auth.uid())::text = "USER_ID"::text)
  WITH CHECK ((select auth.uid())::text = "USER_ID"::text);

-- ============================================================
-- Admin & Support system (INQUIRY / INQUIRY_REPLY / EVENT_LOG)
-- Run this manually in the Supabase SQL Editor.
--
-- Access model:
--   * INQUIRY / INQUIRY_REPLY: owner-only read & insert. Admin access
--     goes through service-role API routes (bypasses RLS), so no
--     admin policies are needed here.
--   * EVENT_LOG: authenticated insert-only (own USER_ID). No SELECT
--     policy at all — only the service-role server can read it.
-- ============================================================

CREATE TABLE IF NOT EXISTS public."INQUIRY" (
    "INQUIRY_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "USER_ID"    uuid NOT NULL,
    "CATEGORY"   text NOT NULL DEFAULT 'GENERAL',  -- COMPLAINT | SUGGESTION | BUG | GENERAL
    "TITLE"      text NOT NULL,
    "CONTENT"    text NOT NULL,
    "STATUS"     text NOT NULL DEFAULT 'OPEN',     -- OPEN | ANSWERED | CLOSED
    "PLATFORM"   text NOT NULL DEFAULT 'WEB',      -- WEB | MOBILE
    "CREATED_AT" timestamp with time zone DEFAULT now(),
    "UPDATED_AT" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."INQUIRY_REPLY" (
    "REPLY_ID"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "INQUIRY_ID" bigint NOT NULL REFERENCES public."INQUIRY"("INQUIRY_ID") ON DELETE CASCADE,
    "USER_ID"    uuid,
    "IS_ADMIN"   boolean NOT NULL DEFAULT false,
    "CONTENT"    text NOT NULL,
    "CREATED_AT" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."EVENT_LOG" (
    "EVENT_ID"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EVENT_TYPE" text NOT NULL,                    -- LOGIN | SEARCH | SCAN | ALBUM_ADD | WISH_ADD | SHARE
    "USER_ID"    uuid,
    "PLATFORM"   text NOT NULL DEFAULT 'WEB',      -- WEB | MOBILE
    "META"       jsonb,
    "CREATED_AT" timestamp with time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "idx_event_log_type_created" ON public."EVENT_LOG" ("EVENT_TYPE", "CREATED_AT");
CREATE INDEX IF NOT EXISTS "idx_event_log_created"      ON public."EVENT_LOG" ("CREATED_AT");
CREATE INDEX IF NOT EXISTS "idx_inquiry_user_created"   ON public."INQUIRY" ("USER_ID", "CREATED_AT" DESC);
CREATE INDEX IF NOT EXISTS "idx_inquiry_reply_parent"   ON public."INQUIRY_REPLY" ("INQUIRY_ID");

-- INQUIRY: owner-only read / owner-only insert / no client update-delete
ALTER TABLE public."INQUIRY" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "inquiry_select_own" ON public."INQUIRY";
DROP POLICY IF EXISTS "inquiry_insert_own" ON public."INQUIRY";
CREATE POLICY "inquiry_select_own" ON public."INQUIRY" FOR SELECT TO authenticated
  USING ((select auth.uid()) = "USER_ID");
CREATE POLICY "inquiry_insert_own" ON public."INQUIRY" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = "USER_ID" AND "STATUS" = 'OPEN');

-- INQUIRY_REPLY: readable by the inquiry owner; users can only add their
-- own non-admin replies (IS_ADMIN can't be forged from the client)
ALTER TABLE public."INQUIRY_REPLY" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "inquiry_reply_select_own" ON public."INQUIRY_REPLY";
DROP POLICY IF EXISTS "inquiry_reply_insert_own" ON public."INQUIRY_REPLY";
CREATE POLICY "inquiry_reply_select_own" ON public."INQUIRY_REPLY" FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public."INQUIRY" i
                 WHERE i."INQUIRY_ID" = "INQUIRY_REPLY"."INQUIRY_ID"
                   AND i."USER_ID" = (select auth.uid())));
CREATE POLICY "inquiry_reply_insert_own" ON public."INQUIRY_REPLY" FOR INSERT TO authenticated
  WITH CHECK ("IS_ADMIN" = false AND (select auth.uid()) = "USER_ID"
              AND EXISTS (SELECT 1 FROM public."INQUIRY" i
                          WHERE i."INQUIRY_ID" = "INQUIRY_REPLY"."INQUIRY_ID"
                            AND i."USER_ID" = (select auth.uid())));

-- EVENT_LOG: authenticated insert-only (own rows), intentionally NO select
-- policy — analytics reads happen exclusively through service-role routes
ALTER TABLE public."EVENT_LOG" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "event_log_insert_own" ON public."EVENT_LOG";
CREATE POLICY "event_log_insert_own" ON public."EVENT_LOG" FOR INSERT TO authenticated
  WITH CHECK ((select auth.uid()) = "USER_ID");

-- Grant admin role (run ONCE for your own account, then sign out & back in;
-- app_metadata is only writable with the service role, so users can't
-- self-promote — do NOT put the role in user_metadata)
-- UPDATE auth.users
--   SET raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb) || '{"role":"admin"}'
--   WHERE email = 'yjw127588@gmail.com';

-- ── Acquisition tracking: allow anonymous VISIT events ─────────
-- Landing/public-dashboard visits happen before login, so the anon role
-- may insert EVENT_LOG rows — but ONLY type VISIT with a null USER_ID
-- (prevents forging other users' activity). Run in the SQL Editor.
DROP POLICY IF EXISTS "event_log_insert_visit_anon" ON public."EVENT_LOG";
CREATE POLICY "event_log_insert_visit_anon" ON public."EVENT_LOG" FOR INSERT TO anon
  WITH CHECK ("EVENT_TYPE" = 'VISIT' AND "USER_ID" IS NULL);
